- src/elements/text-input/src/common.tsx
> Fix invariant violation when importing mask-input

- src/elements/radio-group/src/stories.tsx
- src/elements/tile-input/src/stories.tsx
> Fix radio stories

- src/elements/icon/src/filters.tsx
- src/elements/icon/src/index.tsx
- src/elements/icon/src/stories.tsx
- src/elements/tile-input/src/stories.tsx
> Add new filters icon

- src/elements/bullet-list-highlight/package.json
- src/elements/bullet-list-timeline/package.json
- src/elements/button/package.json
- src/elements/drop-down/package.json
- src/elements/frozen-input/package.json
- src/elements/icon/package.json
- src/elements/imgix-image/package.json
- src/elements/input-alert/package.json
- src/elements/input/package.json
- src/elements/loading-spinner/package.json
- src/elements/progress-bar/package.json
- src/elements/radio-group/package.json
- src/elements/radio-input/package.json
- src/elements/side-drawer/package.json
- src/elements/tile-input/package.json
- src/styles/package.json
Twice because the tags already existed for the first one. (?)
Successfully published:
- @uswitch/trustyle.bullet-list-highlight@0.2.15
- @uswitch/trustyle.bullet-list-timeline@0.2.15
- @uswitch/trustyle.button@0.4.12
- @uswitch/trustyle.drop-down@0.4.15
- @uswitch/trustyle.frozen-input@0.3.15
- @uswitch/trustyle.icon@0.2.15
- @uswitch/trustyle.imgix-image@0.1.12
- @uswitch/trustyle.input-alert@0.2.15
- @uswitch/trustyle.input@0.3.15
- @uswitch/trustyle.loading-spinner@0.2.15
- @uswitch/trustyle.progress-bar@0.2.15
- @uswitch/trustyle.radio-group@0.1.18
- @uswitch/trustyle.radio-input@1.0.14
- @uswitch/trustyle.side-drawer@0.2.3
- @uswitch/trustyle.tile-input@1.0.14
- @uswitch/trustyle.styles@0.3.15
> Publish 8496787

- src/elements/button-link/.npmignore
- src/elements/button-link/package-lock.json
- src/elements/button-link/package.json
- src/elements/button-link/src/index.tsx
- src/elements/button-link/src/stories.tsx
- src/elements/button-link/src/styles.ts
- src/elements/button-link/tsconfig.json
there wasn't an onClick for the ternery anchor in the current button (because the props were extending Button HTML attributes and couldnt be applied to an anchor) so I made a whole new component
> feat: add a button link, so that you can pass an onClick to an anchor

- .storybook/config.js
- src/elements/progress-bar/package-lock.json
- src/elements/progress-bar/package.json
- src/elements/progress-bar/src/styles.ts
- src/styles/package-lock.json
- src/styles/package.json
- src/styles/src/index.ts
- src/styles/src/media-queries.ts
Add breakpoints and logic for breakpoints
> Tablet progress bar

- src/elements/bullet-list-highlight/package.json
- src/elements/bullet-list-timeline/package.json
- src/elements/button-link/package.json
- src/elements/button/package.json
- src/elements/drop-down/package.json
- src/elements/frozen-input/package.json
- src/elements/icon/package.json
- src/elements/input-alert/package.json
- src/elements/input/package.json
- src/elements/loading-spinner/package.json
- src/elements/progress-bar/package.json
- src/elements/radio-input/package.json
- src/elements/side-drawer/package.json
- src/elements/tile-input/package.json
- src/layout/grid/package.json
- src/styles/package.json
- @uswitch/trustyle.bullet-list-highlight@0.2.27
- @uswitch/trustyle.bullet-list-timeline@0.2.23
- @uswitch/trustyle.button-link@0.2.6
- @uswitch/trustyle.button@0.5.6
- @uswitch/trustyle.drop-down@0.4.28
- @uswitch/trustyle.frozen-input@0.3.27
- @uswitch/trustyle.icon@0.2.27
- @uswitch/trustyle.input-alert@0.2.23
- @uswitch/trustyle.input@0.3.27
- @uswitch/trustyle.loading-spinner@0.2.23
- @uswitch/trustyle.progress-bar@0.2.24
- @uswitch/trustyle.radio-input@1.0.22
- @uswitch/trustyle.side-drawer@0.2.15
- @uswitch/trustyle.tile-input@1.0.22
- @uswitch/trustyle.grid@0.2.6
- @uswitch/trustyle.styles@0.4.5
> Publish british-racing-green color

- src/elements/drop-down/package.json
- @uswitch/trustyle.drop-down@0.4.32
> Publish drop-down passing refs

- src/elements/radio-input/src/index.tsx
- src/elements/radio-input/src/stories.tsx
- src/elements/radio-input/src/styles.ts
> Add default padding to radio inputs

- src/elements/radio-input/src/styles.ts
Margins have been removed as they should now be specified using the new
layout components.
> Make RadioInput a block element

- src/elements/button/src/index.tsx
Add the missing cursor pointer
> fix: fix the missing cursor pointer on button

- lerna.json
- src/elements/button/package-lock.json
- src/elements/checkbox-input/package-lock.json
- src/elements/fieldset/package-lock.json
- src/elements/tile-input/package-lock.json
- src/layout/grid/package-lock.json
- src/themes/money/package-lock.json
- src/themes/money/package.json
- src/themes/save-on-energy/package-lock.json
- src/themes/save-on-energy/package.json
- src/themes/uswitch/package-lock.json
- src/themes/uswitch/package.json
> fix: fix lerna setup

- src/elements/button/src/stories.tsx
- src/themes/money/theme.json
Changed the buttons:
- Updated the colours, removed the gradient
- Added disabled, hover, focus, and active states
- Increased padding
> Update money button theme to match new design

- src/elements/button/src/index.tsx
- src/elements/frozen-input/src/index.tsx
- src/elements/list/package-lock.json
- src/elements/list/package.json
- src/elements/list/src/index.tsx
- src/elements/list/src/stories.tsx
- src/elements/list/tsconfig.json
- src/themes/money/theme.json
- src/utils/theme-selector.ts
> feat: add list component

- src/elements/button-link/package-lock.json
- src/elements/button-link/package.json
- src/elements/button-link/src/index.tsx
- src/elements/button-link/src/stories.tsx
- src/elements/button/src/index.tsx
- Made button link component match the button component
- Remove unused `href` prop from button component
> feat: make button link component themeable

- .drone.yml
Run the build on each PR so we dont merge things that break the build
> feat: add test build

- .storybook/config.js
- src/elements/bullet-list-timeline/src/styles.ts
- src/elements/button-link/package-lock.json
- src/elements/button-link/package.json
- src/elements/button-link/src/stories.tsx
- src/elements/button/package.json
- src/elements/button/src/stories.tsx
- src/elements/checkbox-input/src/styles.ts
- src/elements/drop-down/src/styles.ts
- src/elements/fieldset/src/styles.ts
- src/elements/frozen-input/src/styles.ts
- src/elements/global-styles/package-lock.json
- src/elements/global-styles/package.json
- src/elements/global-styles/src/index.tsx
- src/elements/global-styles/src/stories.tsx
- src/elements/global-styles/tsconfig.json
- src/elements/icon/src/styles.ts
- src/elements/input-alert/src/styles.ts
- src/elements/input/src/styles.ts
- src/elements/loading-spinner/src/styles.ts
- src/elements/radio-input/src/styles.ts
- src/elements/side-drawer/src/styles.ts
- src/elements/tile-input/src/styles.ts
- src/styles/src/inputs.ts
- src/styles/src/typography.ts
- Create GlobalStyles element
- Move global typography styles into new component
- Add normalize.css
- Move theme-ui to a peer dependency and remove redundant `ThemeProvider` calls
> feat: create GlobalStyles element and add normalize.css

- _element-template/package.json
- _element-template/src/index.tsx
- _element-template/src/stories.tsx
I kept replicating these every time I made a component, figure it's better to have in the template instead :)
> Added basic tsx files to template, and package.json updates

- src/elements/input/src/index.tsx
- src/elements/input/src/stories.tsx
This makes it possible to do things like strip whitespace from the
exposed input value, while leaving the value displayed in the DOM as
whatever the user typed.
> Add postprocess prop to <Input>

- src/elements/call-out/.npmignore
- src/elements/call-out/package-lock.json
- src/elements/call-out/package.json
- src/elements/call-out/src/index.tsx
- src/elements/call-out/src/stories.tsx
- src/elements/call-out/tsconfig.json
- src/themes/money/theme.json
- src/themes/uswitch/theme.json
money:
uswitch:
There's some minor styling differences, but they're more generic stuff so they're out of the scope of this PR.
> Add call out component

- .storybook/config.js
- .storybook/preview-head.html
- src/elements/cta/.npmignore
- src/elements/cta/package-lock.json
- src/elements/cta/package.json
- src/elements/cta/src/index.tsx
- src/elements/cta/src/stories.tsx
- src/elements/cta/tsconfig.json
- src/themes/money/theme.json
- src/themes/uswitch/theme.json
money:
uswitch:
The Uswitch one doesn't match the design as the fonts, colours, and primary button styling don't match figma - outside of the scope of this PR.
> Add CTA component

- src/elements/global-styles/src/stories.tsx
- src/themes/money/theme.json
- src/themes/uswitch/theme.json
money:
uswitch:
uswitch will look nicer when the uswitch theme is done - my next task!
> Add quote styling

- src/elements/pagination/.npmignore
- src/elements/pagination/package-lock.json
- src/elements/pagination/package.json
- src/elements/pagination/src/index.tsx
- src/elements/pagination/src/stories.tsx
- src/elements/pagination/tsconfig.json
- src/themes/money/theme.json
- src/themes/uswitch/theme.json
> Added pagination component

- lerna.json
- src/helpers/date/.npmignore
- src/helpers/date/package-lock.json
- src/helpers/date/package.json
- src/helpers/date/src/index.ts
- src/helpers/date/tsconfig.json
Install step is failing on that branch because the author component depends on this one so npm is erroring
> Add date helper from author component branch

- src/helpers/date/package-lock.json
- src/helpers/date/package.json
This is the only one that managed to publish - manually committing so that the publish script works next time.
> Partial publish - date only

- src/themes/money/theme.json
This adds a link to the money theme
> feat: add link to money theme

- publish.sh
Currently creating a new lerna repo to test this with :)
update: it works! https://github.com/uswitch/test-lerna-publish/pull/4
> Fix publish script so that it doesn't update everything every time

- src/elements/call-out/src/index.tsx
- src/elements/category/src/index.tsx
- src/elements/pagination/src/index.tsx
There's still a couple in the pagination component where the logic is a bit more complicated, and the CTA component has been changed in the CTA component that's open at the moment.
> Change object spread operator in sx props to use variant instead

- src/themes/journey/index.js
- src/themes/journey/package-lock.json
- src/themes/journey/package.json
- src/themes/journey/theme.json
Journey is pre re-brand, but we need a Trustyle theme so we can release some new components. This PR captures the uSwitch theme before it was (partially) rebranded.
This is a:
> Add Journey theme

- src/elements/funnel-progress/package-lock.json
Need to update `package-lock.json` for new component as it prevents publish.
This is a:
> Update funnel-progress package-lock

- src/elements/checkbox-input/package-lock.json
- src/elements/checkbox-input/package.json
- src/elements/fieldset/package-lock.json
- src/elements/fieldset/package.json
- src/elements/tile-input/package-lock.json
- src/elements/tile-input/package.json
- src/layout/grid/package-lock.json
- src/layout/grid/package.json
- @uswitch/trustyle.checkbox-input@0.0.22
- @uswitch/trustyle.fieldset@0.0.22
- @uswitch/trustyle.tile-input@1.0.49
- @uswitch/trustyle.grid@2.0.0
update versions
This is a:
> (With package-lock.json changes) Publish

- .storybook/preview-body.html
- src/layout/grid/src/stories.tsx
restore body padding and just remove it for grid story
This is a:
> restore body padding and just remove it for grid story

- src/elements/cta/src/index.tsx
- src/elements/cta/src/stories.tsx
- src/themes/money/theme.json
- src/themes/uswitch/theme.json
money mobile:
money desktop:
uswitch mobile:
uswitch desktop:
> Update CTA component design to match changes in figma

- src/themes/journey/theme.json
- src/themes/money/theme.json
> typeography and container updates

- src/themes/money/theme.json
> Reduce money lg container to be 1024px

- package-lock.json
- package.json
> add deploy-storybook script

- src/layout/grid/src/styles.ts
- src/styles/src/media-queries.ts
The breakpoints were smaller than the container widths.
> fix breakpoints to match container widths

- src/themes/uswitch/theme.json
> Add fontWeight 500 to anchor on uswitch theme

- package-lock.json
- src/elements/table/package-lock.json
- src/elements/table/package.json
- src/elements/table/src/__snapshots__/stories.storyshot
- src/elements/table/src/index.tsx
- src/elements/table/src/stories.tsx
- src/elements/table/tsconfig.json
- src/themes/money/theme.json
- src/themes/uswitch/theme.json
Add the table component
Money
Uswitch
This is a:
> feat: add table component

- src/themes/uswitch/theme.json
Was broken by https://github.com/uswitch/trustyle/pull/247.
This is a:
> Fix accordion styling with uswitch brand

- src/elements/link-list/package-lock.json
- src/elements/link-list/package.json
- src/elements/link-list/src/index.tsx
- src/elements/link-list/src/stories.tsx
- src/elements/link-list/tsconfig.json
New Link list component
Uswitch
Money
This is a:
> feat: add link list

- src/compounds/article-intro/.npmignore
- src/compounds/article-intro/package-lock.json
- src/compounds/article-intro/package.json
- src/compounds/article-intro/src/index.tsx
- src/compounds/article-intro/src/stories.tsx
- src/compounds/article-intro/tsconfig.json
- src/themes/money/theme.json
> Added article intro component

- .drone.yml
> temporarily remove percy in drone until we pay for it

- src/compounds/article-intro/package-lock.json
- src/compounds/article-intro/package.json
> feat: rename article intro component

- src/elements/imgix-image/src/index.tsx
> change src type to string, import module from correct location

- src/elements/list/src/index.tsx
- src/themes/money/theme.json
> Made list spacing match design

- .gitignore
- src/compounds/article-intro/src/index.tsx
- src/elements/author/src/index.tsx
- src/elements/breadcrumbs/src/index.tsx
- src/themes/money/theme.json
- src/themes/uswitch/theme.json
Bunch of small fixes (mostly spacing)
This is a:
> Bunch of small fixes

- src/elements/author/src/index.tsx
- src/elements/author/src/stories.tsx
- src/themes/money/theme.json
Fix links on author header
This is a:
> feat: add author links

- src/compounds/article-intro/package.json
- src/elements/author/package.json
- src/elements/card/package.json
- src/elements/imgix-image/package.json
- src/elements/input/package.json
- src/elements/input/src/index.tsx
- src/layout/arrangement/package.json
- src/themes/money/package.json
Makes a dummy change and adds tags to packages that got package-lock.json removed, so it gets versions in sync.
Hopefully after this is merged, `npx lerna version` will pick up changes correctly.
> Test branch

- src/elements/card/package.json
- src/elements/card/src/index.tsx
> make entire card an anchor

- src/compounds/article-intro/src/stories.tsx
Update the story so the url is on the arrticle header 
> feat: update story for article header

- src/compounds/article-intro/package.json
- src/elements/author/package.json
- src/elements/author/src/index.tsx
- src/themes/money/package.json
- src/themes/money/theme.json
> fix author link styles

- README.md
- publish.sh
- src/elements/drop-down/package.json
- src/elements/drop-down/src/styles.ts
One last CI publishing test. Everything seems to be working well and tags in sync with npm.
> Update dropdown - CI Publish test

- src/elements/card/package.json
- src/elements/card/src/index.tsx
> add hover state to cards

- src/elements/breadcrumbs/package.json
- src/elements/cta/package.json
- src/elements/cta/src/index.tsx
- src/elements/cta/src/stories.tsx
- src/themes/money/theme.json
- src/themes/uswitch/theme.json
> Add hero and hero-white-bg variants to cta component

- src/compounds/side-nav/package.json
- src/compounds/side-nav/src/index.tsx
- src/elements/accordion/package.json
- src/elements/accordion/src/index.tsx
- src/elements/accordion/src/stories.tsx
- src/elements/breadcrumbs/package.json
- src/elements/cta/package.json
- src/elements/embedded-video/package.json
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/uswitch/package.json
Update accodion to match design
> fix: update accordion style

- src/compounds/side-nav/package.json
- src/elements/accordion/package.json
- src/elements/accordion/src/index.tsx
- src/elements/embedded-video/package.json
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Fixes uswitch and money accordion
> fix: issues with accordion styles

- src/compounds/side-nav/package.json
- src/elements/accordion/package.json
- src/elements/accordion/src/index.tsx
- src/elements/accordion/src/stories.tsx
- src/elements/embedded-video/package.json
Add last child and first child no margin
> fix: last child and first child in accordion

- src/compounds/side-nav/package.json
- src/elements/accordion/package.json
- src/elements/embedded-video/package.json
- src/elements/toggle-switch/package.json
- src/themes/money/package.json
- src/themes/save-on-energy/package.json
- src/themes/uswitch/package.json
- src/utils/palette/package.json
- @uswitch/trustyle.side-nav@0.2.6
- @uswitch/trustyle.accordion@0.2.5
- @uswitch/trustyle.embedded-video@0.2.5
- @uswitch/trustyle.toggle-switch@1.1.0
- @uswitch/trustyle.money-theme@0.6.0
- @uswitch/trustyle.save-on-energy-theme@0.2.0
- @uswitch/trustyle.uswitch-theme@0.3.0
- @uswitch/trustyle-utils.palette@1.0.0
To publish `ToggleSwitch` and `Palette`
> Publish Toggle Switch & Palette util

- src/compounds/side-nav/package.json
- src/elements/accordion/package.json
- src/elements/call-out/package.json
- src/elements/call-out/src/index.tsx
- src/elements/call-out/src/stories.tsx
- src/elements/embedded-video/package.json
- src/elements/toggle-switch/package.json
- src/elements/toggle-switch/src/stories.tsx
- src/themes/money/package.json
- src/themes/save-on-energy/package.json
- src/themes/uswitch/package.json
- src/utils/palette/package.json
All the `call-out` module to be painted
Uswitch base
Money base
Uswitch with Pallette
> Callout painting

- src/compounds/side-nav/package.json
- src/compounds/side-nav/src/index.tsx
- src/elements/accordion/package.json
- src/elements/accordion/src/index.tsx
- src/elements/accordion/src/stories.tsx
- src/elements/card/package.json
- src/elements/cta/package.json
- src/elements/cta/src/index.tsx
- src/elements/embedded-video/package.json
- src/elements/imgix-image/package.json
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/save-on-energy/package.json
- src/themes/uswitch/package.json
- src/utils/get/package-lock.json
Fixes a few minor issues that came out of design review.
> Small layout tweaks

- src/utils/get/package.json
> Fix ts:main path for trustyle-utils.get

- src/elements/breadcrumbs/package.json
- src/elements/breadcrumbs/src/index.tsx
- src/elements/cta/package.json
- src/utils/get/package.json
Increas X margins on breadcrumb up a notch
> change margin to xs

- src/themes/money/theme.json
Adds to money theme to style cards/
Old:
New:
> adds styles for money cards

- src/elements/author-profile/.npmignore
- src/elements/author-profile/.npmrc
- src/elements/author-profile/package.json
- src/elements/author-profile/src/index.tsx
- src/elements/author-profile/src/stories.tsx
- src/elements/author-profile/tsconfig.json
Adds an Author Profile component with name, image and description for author pages
> adds author profile component

- src/elements/author-profile/package.json
- src/elements/author-profile/src/index.tsx
- src/themes/money/package.json
- src/themes/money/theme.json
> Author Profile styling tweaks

- src/elements/category/package.json
- src/elements/category/src/index.tsx
- src/elements/category/src/stories.tsx
- src/themes/money/package.json
- src/themes/money/theme.json
> Optionally add breadcrumbs to category headings

- src/elements/category/package.json
- src/elements/category/src/index.tsx
Switches the grid to the new grid
> feat: switch category header to use correct grid

- src/elements/card/package.json
- src/elements/card/src/stories.tsx
- src/themes/money/package.json
- src/themes/money/theme.json
> feat: update card theme

- src/elements/category/package.json
- src/layout/flex-grid/package.json
- src/layout/flex-grid/src/index.tsx
> set overflowY on rows to be visible"

- src/compounds/ad-banner/package.json
- src/compounds/ad-banner/src/index.tsx
- src/compounds/ad-banner/src/stories.tsx
- src/elements/badge/src/stories.tsx
- src/elements/button/package.json
- src/elements/card/package.json
- src/themes/money/package.json
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> New badge variant

- src/compounds/ad-banner/package.json
- src/compounds/ad-banner/src/index.tsx
- src/compounds/ad-banner/src/stories.tsx
Adds a container for the backgroundImage prop
> Finalise ad banner

- src/compounds/ad-banner/package.json
- src/elements/card/package.json
- src/elements/card/src/index.tsx
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Move the anchors and fix the image sizes
> feat: update card to move anchor and fix img

- src/compounds/ad-banner/package.json
- src/compounds/ad-banner/src/index.tsx
Corrected issues with padding and ensured it matched figma.
> Ad banner changes

- src/elements/button/package.json
- src/elements/button/src/index.tsx
> Update to use get for all other buttons.prop reads

- src/compounds/ad-banner/package.json
- src/compounds/ad-banner/src/index.tsx
- src/compounds/ad-banner/src/stories.tsx
Added Imgix element to Ad Banner for Sponsor Logo and optional additional Image.
> Ad banner imgix

- src/compounds/ad-banner/package.json
- src/compounds/ad-banner/src/index.tsx
- src/elements/button/package.json
- src/elements/card/package.json
- src/elements/imgix-image/package.json
- src/elements/imgix-image/src/index.tsx
Imgix element now able to use Lazy Loading correctly. Lazysize added as dependency. 
> Imgix lazyload

- src/compounds/ad-banner/package.json
- src/compounds/ad-banner/src/index.tsx
- src/compounds/ad-banner/src/stories.tsx
Padding changes to badge on Ad Banner Compound at Designers request.
> Padding changes ad banner

- src/elements/hero/src/index.tsx
- src/elements/hero/src/stories.tsx
- src/layout/flex-grid/src/index.tsx
Breaking change. Means we'll be able to use this component for the new money homepage.
> Move responsibility of width into hero component

- src/elements/card/package.json
- src/elements/category/package.json
- src/elements/hero/package.json
- src/layout/flex-grid/package.json
- @uswitch/trustyle.card@0.2.11
- @uswitch/trustyle.category@1.1.6
- @uswitch/trustyle.hero@2.0.0
- @uswitch/trustyle.flex-grid@1.0.0
😬
> Release commit for #376

- src/elements/card/package.json
- src/elements/category/package.json
- src/layout/flex-grid/package.json
- src/layout/flex-grid/src/index.tsx
> Update container max width calculations to allow responsive

- src/elements/card/package.json
- src/elements/category/package.json
- src/layout/flex-grid/package.json
- src/themes/bankrate/.npmrc
- src/themes/bankrate/index.js
- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
Copies money theme to create bankrate
> feat: add bankrate theme

- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
- src/themes/money/package.json
- src/themes/money/theme.json
> feat: add rich text module span

- src/compounds/sponsored-product/package.json
- src/compounds/sponsored-product/src/index.tsx
- src/elements/awards-tag/package.json
- src/elements/awards-tag/src/index.tsx
- src/elements/primary-info-block/package.json
- src/elements/sponsored-by-tag/package.json
- src/elements/usp-tag/package.json
- src/elements/usp-tag/src/index.tsx
- src/themes/uswitch/package.json
Fixes to sponsored product compound - size of CTA, spacing between elements, wrapped in anchor tag to make clickable
> Sponsored product fixes

- .drone.yml
This reverts commit 8501084994c1bb291ba28d7e5ca12c3b754e8d7b.
> Revert "temporarily remove percy in drone until we pay for it"

- src/compounds/sponsored-product/package.json
- src/elements/input/package.json
- src/elements/input/src/index.tsx
Related to the previous PR I've removed the type and let it be handled by React.InputHTMLAttributes<HTMLInputElement>.
Previous PR: https://github.com/uswitch/trustyle/pull/389
> added number input type

- src/elements/card/package.json
- src/elements/category/package.json
- src/layout/flex-grid/package.json
- src/layout/flex-grid/src/index.tsx
- src/layout/flex-grid/src/stories.tsx
This might be too specific to live here - thoughts appreciated!
> Add GridFromJson component to flex-grid layout

- src/elements/card/package.json
- src/elements/category/package.json
- src/layout/flex-grid/package.json
- src/layout/flex-grid/src/index.tsx
> turn on wrapping by default and remove overflow

- src/compounds/sponsored-product-rate-table/.npmignore
- src/compounds/sponsored-product-rate-table/.npmrc
- src/compounds/sponsored-product-rate-table/package.json
- src/compounds/sponsored-product-rate-table/src/index.tsx
- src/compounds/sponsored-product-rate-table/src/stories.tsx
- src/compounds/sponsored-product-rate-table/tsconfig.json
- src/compounds/sponsored-product/package.json
- src/compounds/sponsored-product/src/index.tsx
- src/elements/awards-tag/package.json
- src/elements/awards-tag/src/index.tsx
- src/elements/primary-info-block/package.json
- src/elements/primary-info-block/src/index.tsx
- src/elements/sponsored-by-tag/package.json
- src/elements/sponsored-by-tag/src/index.tsx
Created sponsored product rate table compound and made some minor updates to sponsored product, awards tag, sponsored by tag and primary info block such as allowing element to take sx prop
- [ x ] A new component
> Sponsored product rate table

- src/themes/money/package.json
- src/themes/money/theme.json
Update money theme for new buttons collection.
> Add spacing for button collections for money

- src/elements/hero/package.json
- src/elements/hero/src/index.tsx
- src/elements/hero/src/stories.tsx
> Mobile here changes for money home page

- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
> Bankrate theme cookie page

- src/compounds/ad-banner/package.json
- src/compounds/sponsored-product-rate-table/package.json
- src/compounds/sponsored-product/package.json
- src/elements/button-link/package.json
- src/elements/button-link/src/index.tsx
- src/elements/cta/package.json
- src/elements/icon-tile/package.json
- src/elements/icon-tile/src/index.tsx
- src/themes/money/package.json
- src/themes/money/theme.json
See commit messages for description of changes!
> Visual changes for homepage

- src/compounds/sponsored-product-rate-table/package.json
- src/compounds/sponsored-product-rate-table/src/index.tsx
- src/compounds/sponsored-product/package.json
- src/compounds/sponsored-product/src/index.tsx
- src/elements/usp-tag/package.json
- src/elements/usp-tag/src/index.tsx
Fixes for sponsored product table compound
> Sponsored slots fixes

- src/helpers/date/package.json
> fix date component not working in development

- .drone.yml
- package-lock.json
- package.json
- scripts/slack-unpublished.js
Will post something like the last message when someone merges without versioning.
> Add drone script to post to slack when unversioned changes merged

- src/compounds/product-table/package.json
- src/compounds/product-table/src/generics.ts
- src/compounds/product-table/src/stories.tsx
Implement basic `data` formatter. Formats `100` megabytes into `100MB` and `1000` megabytes into `1GB`
> Add basic data formatter

- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
updating bankrate grid to match the includes
> fix bankrate grid to match header and footer

- src/compounds/article-intro/package.json
- src/compounds/article-intro/src/index.tsx
- src/themes/money/package.json
- src/themes/money/theme.json
Moved articleIntro under compounds key in theme and updated all references (in non breaking way)
> moved article Intro to be under compounds key in theme

- src/compounds/side-nav/package.json
- src/compounds/sponsored-product-rate-table/package.json
- src/compounds/sponsored-product/package.json
- src/compounds/testimonial-card/.npmignore
- src/compounds/testimonial-card/.npmrc
- src/compounds/testimonial-card/package.json
- src/compounds/testimonial-card/src/index.tsx
- src/compounds/testimonial-card/src/stories.tsx
- src/compounds/testimonial-card/tsconfig.json
- src/elements/accordion/package.json
- src/elements/breadcrumbs/package.json
- src/elements/bullet-list-highlight/package.json
- src/elements/call-out/package.json
- src/elements/category/package.json
- src/elements/drop-down/package.json
- src/elements/embedded-video/package.json
- src/elements/frozen-input/package.json
- src/elements/funnel-progress/package.json
- src/elements/icon/package.json
- src/elements/icon/src/index.tsx
- src/elements/icon/src/person.tsx
- src/elements/icon/src/stories.tsx
- src/elements/input/package.json
- src/elements/pagination/package.json
- src/elements/side-drawer/package.json
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Add testimonial cards for use in uswitch energy homepage
- [X ] A new component
> Testimonial card

- src/themes/money/package.json
- src/themes/money/theme.json
> Update money theme

- src/elements/card/package.json
- src/elements/category/package.json
- src/layout/flex-grid/package.json
- src/layout/flex-grid/src/index.tsx
- src/themes/money/package.json
- src/themes/money/theme.json
> Increase flex-grid vertical gutter for money

- src/themes/money/package.json
- src/themes/money/theme.json
> Update image callout

- src/elements/category/src/index.tsx
- src/elements/category/src/stories.tsx
- src/themes/money/theme.json
ticket: https://app.asana.com/0/1153286245702289/1173416339963906
- Text now spans 50% on money theme (and other themes can change it if
they wish)
- Background gradient has been updated to match the hero
> Design updates to category component

- src/elements/category/package.json
- src/themes/money/package.json
- @uswitch/trustyle.category@1.2.0
- @uswitch/trustyle.money-theme@0.11.7
> Publish category component

- src/elements/list/package.json
- src/elements/list/src/index.tsx
- src/elements/list/src/stories.tsx
https://app.asana.com/0/1153286245702289/1173221176954873
> Fix spacing issue on lists with more than ten items

- src/elements/card/package.json
- src/elements/card/src/index.tsx
adds ability to pass styling to linkText in card
> adds ability to pass styling to linkText in card

- src/compounds/sponsored-product-rate-table/package.json
- src/compounds/sponsored-product/package.json
- src/elements/call-out/package.json
- src/elements/primary-info-block/package.json
- src/elements/toggle-switch/package.json
- src/elements/toggle-switch/src/index.tsx
- src/utils/palette/package.json
- src/utils/palette/src/index.tsx
- [X ] Component maintenance: improvement / bug fix / etc
> Overflow hidden on palette to prevent space between backgrounds

- src/elements/input-alert/package.json
- src/elements/input-alert/src/index.tsx
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> Make input-alert themeable

- src/elements/card/package.json
- src/elements/card/src/index.tsx
- src/elements/card/src/stories.tsx
adds image optimisation to card
> adds image optimization to card

- src/elements/card/package.json
- src/elements/card/src/index.tsx
- src/elements/card/src/stories.tsx
> card image contain

- src/elements/input/package.json
- src/elements/input/src/index.tsx
- src/elements/input/src/styles.ts
- src/themes/journey/package.json
- src/themes/journey/theme.json
> feat: make input themeable

- src/elements/drop-down/package.json
- src/elements/drop-down/src/index.tsx
- src/elements/drop-down/src/styles.ts
- src/themes/journey/package.json
- src/themes/journey/theme.json
> feat: themeable drop-down

- src/themes/money/package.json
- src/themes/money/theme.json
> fix: issues with money styling of tables

- src/elements/call-out/package.json
- src/elements/call-out/src/index.tsx
- src/elements/call-out/src/stories.tsx
> feat: allow bold callout

- src/compounds/product-table/src/components/data-range.tsx
- src/compounds/product-table/src/components/data-text-subscript.tsx
- src/compounds/product-table/src/components/data-value.tsx
- src/compounds/product-table/src/index.tsx
- src/compounds/product-table/src/stories.tsx
Expose the formatting logic for reuse
> Add plain text formatters for reuse in HTML tables

- src/elements/category/package.json
- src/elements/category/src/index.tsx
- src/elements/category/src/stories.tsx
> add optional image to category

- .drone.yml
properly build only changed packages
> only build changed components

- src/compounds/product-table/package.json
- src/elements/category/package.json
- src/elements/category/src/index.tsx
> category image fix

- package-lock.json
- package.json
> Update preset.env version

- src/compounds/product-table/src/components/row.tsx
- src/compounds/product-table/src/stories.tsx
Adds the ability to add an id tag to the product table row. 
> Add id prop to product table row

- src/compounds/product-table/package.json
- @uswitch/trustyle.product-table@1.4.3
Create new version
> Release v1.4.3

- src/elements/card/src/index.tsx
- src/elements/card/src/stories.tsx
- src/themes/journey/theme.json
- src/themes/money/theme.json
- src/themes/save-on-energy/theme.json
- src/themes/uswitch/theme.json
- Card theme has been removed from journey as it doesn't use cards
- Borders have been removed from uswitch theme as they aren't part of the design (trustyle cards aren't currently being used on uswitch brand)
> Horizontal cards

- src/themes/journey/package.json
- src/themes/journey/theme.json
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
* Remove rounded borders from Journey theme.
* Fix height of buttons to 48px (implements small and large as the same size)
* Add focus style
> Fix Button's Uswitch and Journey theme

- src/compounds/tabs/package.json
- src/compounds/tabs/src/index.tsx
> fix: missing key prop in tabs

- .drone.yml
- src/elements/drop-down/package.json
- src/elements/drop-down/src/index.tsx
- src/elements/drop-down/src/stories.tsx
- src/elements/themed-icon/package.json
- src/elements/themed-icon/tsconfig.json
- src/elements/themed-icon/webpack.config.js
Also added a tiny change to the dropdown component in this PR - it's not worth making another PR for.
> Fix themed-icon build when used in eevee-components

- src/elements/themed-icon/package.json
- src/elements/themed-icon/webpack.config.js
> Fix themed icon component when rendered server-side

- src/elements/icon/src/cross.tsx
- src/elements/icon/src/index.tsx
- src/elements/icon/src/stories.tsx
- src/elements/icon/src/tick.tsx
> Add tick and cross icons

- src/elements/input/src/index.tsx
- src/elements/input/src/styles.ts
- src/themes/bankrate/theme.json
- src/themes/journey/theme.json
- src/themes/money/theme.json
- src/themes/save-on-energy/theme.json
Finishing up making the inputs squared
> Square inputs on journey and uswitch

- src/compounds/carousel/package.json
- src/compounds/interactive-tabs/package.json
- src/compounds/side-nav/package.json
- src/compounds/sponsored-product-rate-table/package.json
- src/compounds/sponsored-product/package.json
- src/compounds/testimonial-card/package.json
- src/elements/accordion/package.json
- src/elements/breadcrumbs/package.json
- src/elements/bullet-list-highlight/package.json
- src/elements/call-out/package.json
- src/elements/category/package.json
- src/elements/drop-down/package.json
- src/elements/embedded-video/package.json
- src/elements/frozen-input/package.json
- src/elements/icon/package.json
- src/elements/input/package.json
- src/elements/pagination/package.json
- src/elements/side-drawer/package.json
> Bump versions

- lerna.json
- src/compounds/carousel/package.json
- src/compounds/interactive-tabs/package.json
- src/compounds/side-nav/package.json
- src/compounds/sponsored-product-rate-table/package.json
- src/compounds/sponsored-product/package.json
- src/compounds/testimonial-card/package.json
- src/elements/accordion/package.json
- src/elements/breadcrumbs/package.json
- src/elements/bullet-list-highlight/package.json
- src/elements/call-out/package.json
- src/elements/category/package.json
- src/elements/drop-down/package.json
- src/elements/embedded-video/package.json
- src/elements/frozen-input/package.json
- src/elements/icon/package.json
- src/elements/input/package.json
- src/elements/pagination/package.json
- src/elements/side-drawer/package.json
> Tell github to skip build for publish commits too

- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> Improve control button styling

- src/elements/toggle-switch/package.json
- src/elements/toggle-switch/src/assets.tsx
- src/elements/toggle-switch/src/index.tsx
- src/elements/toggle-switch/src/stories.tsx
- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/save-on-energy/package.json
- src/themes/save-on-energy/theme.json
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
- src/utils/all-themes.tsx
> Add compact version of toggle switch

- src/elements/toggle-switch/package.json
- src/elements/toggle-switch/src/index.tsx
> Pass className through toggleswitch component

- src/elements/logo-collection/package.json
- src/elements/logo-collection/src/index.tsx
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Adds variant to outer div in logo-collection for additional styling.
> Updates logo-collection to include variant for outer div.

- src/elements/funnel-progress/package.json
- src/elements/funnel-progress/src/index.tsx
> Remove reference to open which does not exist

- src/elements/icon-tile/package.json
- src/elements/logo-collection/package.json
- src/elements/slide-reveal/.npmignore
- src/elements/slide-reveal/.npmrc
- src/elements/slide-reveal/package.json
- src/elements/slide-reveal/src/index.tsx
- src/elements/slide-reveal/src/stories.tsx
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/uswitch/package.json
A component that transitions opening and closing with a slide effect.
> Slide reveal component

- src/themes/money/package.json
- src/themes/money/theme.json
Part of the money homepage redesign
> Update icon tile text colour

- src/themes/journey/package.json
- src/themes/journey/theme.json
Some tweaks to the buttons for journey
> Fix button styling in journey theme

- src/compounds/carousel/package.json
- src/compounds/carousel/src/glider-styles.ts
- src/compounds/carousel/src/index.tsx
- src/compounds/interactive-tabs/package.json
- src/compounds/interactive-tabs/src/index.tsx
- src/compounds/interactive-tabs/src/stories.tsx
- src/compounds/tabs/package.json
- src/compounds/tabs/src/index.tsx
- src/compounds/testimonial-card/package.json
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
- Fix tabs component for SSR
- Styling fixes for carousel (no scrollbar)
- Allow glider settings & event listeners to be passed when using carousel
- Fix issue when responsive carousel shows incorrect number of slides on desktop
- Allow title element to be passed to interactive tabs
- [X ] Component maintenance: improvement / bug fix / etc
> Design fixes

- src/themes/journey/package.json
- src/themes/journey/theme.json
Fix styling issue that caused round corners on focus of the select box
> Fix round corners on the drop downs in journey

- src/elements/card/package.json
- src/elements/logo-collection/package.json
- src/themes/journey/package.json
- src/themes/journey/theme.json
- src/themes/uswitch/package.json
Update the color of the anchor links in the journey theme
> Fix typography new styling

- src/compounds/product-table/package.json
- src/compounds/product-table/src/components/cell-content.tsx
- src/compounds/product-table/src/components/cell-cta.tsx
- src/compounds/product-table/src/stories.tsx
- src/elements/read-more-card/package.json
- src/themes/money/package.json
- src/themes/money/theme.json
> Minor visual changes to product table

- src/elements/drop-down/package.json
- src/elements/frozen-input/package.json
- src/elements/frozen-input/src/index.tsx
- src/elements/input/package.json
- src/themes/bankrate/package.json
- src/themes/journey/package.json
- src/themes/journey/theme.json
> Frozen input text grey

- src/compounds/article-intro/package.json
- src/elements/author/package.json
- src/elements/author/src/index.tsx
- src/elements/author/src/stories.tsx
Dont show a data in the author component if none is provided
> hide no date author

- src/elements/hero-with-background-image/package.json
- src/elements/hero-with-background-image/src/index.tsx
- src/elements/hero-with-background-image/src/stories.tsx
- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
> simplify hero with background image

- src/elements/author-profile/package.json
- src/elements/author-profile/src/index.tsx
- src/elements/author-profile/src/stories.tsx
Extended author profile with email field.
without email( no changes ) -  ![image](https://user-images.githubusercontent.com/66306693/85011592-078fd700-b162-11ea-8e07-e268c9f7ff8c.png)
with email  - 
> Extended author profile with details fields

- src/themes/money/theme.json
> Add missing itemsPerRow

- src/themes/bankrate/package.json
- src/themes/money/package.json
- src/themes/uswitch/package.json
- @uswitch/trustyle.bankrate-theme@1.1.0
- @uswitch/trustyle.money-theme@0.16.0
- @uswitch/trustyle.uswitch-theme@0.16.0
Publish bankrate, money and uswitch themes
> Publish bankrate, money and uswitch themes

- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
> More bankrate theming

- src/elements/frozen-input/src/index.tsx
- src/elements/input/src/index.tsx
- src/elements/input/src/stories.tsx
Wrap Input component in forwardRef to allow a ref to be passed to an Input
> Add forwardRef to Input

- src/elements/drop-down/package.json
- src/elements/drop-down/src/index.tsx
- src/elements/drop-down/src/stories.tsx
- src/themes/journey/package.json
- src/themes/journey/theme.json
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Fix the grey color in the dropdown placeholder.
> Make the placeholder themable and gray-60 on journey theme

- src/elements/drop-down/package.json
- src/elements/funnel-progress/package.json
- src/elements/funnel-progress/src/index.tsx
- src/themes/journey/package.json
- src/themes/money/package.json
- src/themes/uswitch/package.json
Add optional param to funnel progress to remove the bar. This will be used on the journey results step.
> Add prop to hide progress bar on progress funnel

- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
> Update bankrate card

- src/compounds/article-intro/package.json
- src/elements/author/package.json
- src/elements/author/src/index.tsx
- src/elements/list/package.json
- src/elements/list/src/index.tsx
- src/elements/list/src/stories.tsx
- src/elements/read-more-card/package.json
- src/elements/read-more-card/src/index.tsx
- src/elements/read-more-card/src/stories.tsx
- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
> bankrate tweaks

- src/themes/journey/package.json
- src/themes/journey/theme.json
> Change height of the radio buttons for the journey theme

- src/themes/journey/package.json
- src/themes/journey/theme.json
> Make radio 2px smaller on journey

- src/elements/card/package.json
- src/elements/card/src/index.tsx
> Always render description/linkText in card

- src/themes/uswitch-rebrand/.npmrc
- src/themes/uswitch-rebrand/index.js
- src/themes/uswitch-rebrand/package.json
- src/themes/uswitch-rebrand/theme.json
This is the theme that leafeon / journey homepage is using. Adding it to
trustyle so it will be easier to merge it into the existing uswitch
theme.
> Add uswitch-rebrand theme

- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
> update bankrate theme

- src/elements/button/package.json
- src/elements/button/src/index.tsx
- src/themes/journey/package.json
- src/themes/journey/theme.json
Fixes sticky hover bug on mobile
Was not able to test this on simulator but didn't break the existing functionality so I'll be testing it once published. Will fix/revert if doesn't do what's needed.
> Fix sticky hover state on iOS

- src/elements/list/package.json
- src/elements/list/src/index.tsx
Fix issue in Eevee with p being injected in list items
> feat: fix incorrect list spacing

- src/compounds/article-intro/package.json
- src/elements/author/package.json
- src/elements/author/src/index.tsx
> fix comma separator display

- src/compounds/sponsored-product-rate-table/package.json
- src/compounds/sponsored-product/package.json
- src/elements/call-out/package.json
- src/elements/primary-info-block/package.json
- src/elements/toggle-switch/package.json
- src/utils/palette/package.json
- src/utils/palette/src/index.tsx
Before, g's had their bottom sliced:
After:
> add padding to ensure margin is not applied to parent element

- src/themes/uswitch-rebrand/package.json
- src/themes/uswitch-rebrand/theme.json
- Hides scrollbar in FF.
- Fixes margin-bottom on more ways to switch callouts.
- Fixes callout issue for IE11 (energy-journey#1090)
- Add disclaimer text and fix star ratings when field empty
(energy-journey#1088)
> Browser fixes for uswitch-rebrand theme

- package.json
- src/compounds/sponsored-product-rate-table/package.json
- src/compounds/sponsored-product-rate-table/src/index.tsx
- src/themes/uswitch-rebrand/package.json
- src/themes/uswitch-rebrand/theme.json
- src/utils/all-themes.tsx
This PR is merging the new uswitch rebrand theme with the old one as part of getting FS Guides on Leafeon. 
> Merge uswitch and rebrand themes

- src/compounds/sponsored-product-rate-table/package.json
- src/compounds/sponsored-product/package.json
- src/elements/call-out/package.json
- src/elements/primary-info-block/package.json
- src/elements/toggle-switch/package.json
- src/utils/palette/package.json
- src/utils/palette/src/index.tsx
> ensures padding is no overwriting props passed in

- src/compounds/sponsored-product-rate-table/package.json
- src/compounds/sponsored-product/package.json
- src/elements/call-out/package.json
- src/elements/primary-info-block/package.json
- src/elements/toggle-switch/package.json
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
- src/utils/all-themes.tsx
- src/utils/palette/package.json
This is following the merging of the rebrand and the old uswitch themes. The rebrand npm package is no longer needed so the theme has been moved to the original uswitch theme npm package.
> Move rebranded uswitch theme to the uswitch theme npm package

- src/compounds/tabs/package.json
- src/themes/money/package.json
Publish update to tabs component and money theme
> Publish tabs padding

- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
> remove heading height

- .github/workflows/automatic-release.yml
> chore: Remove if statement from automatic release gh action

- lerna.json
> chore: Fix lerna message on publish

- .github/workflows/automatic-release.yml
This is trying to fix the detached HEAD issue with lerna in GH actions
> chore: Use actions checkout v2

- src/elements/hero/CHANGELOG.md
- src/elements/hero/package.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- @uswitch/trustyle.hero@2.4.0
- @uswitch/trustyle.uswitch-theme@0.21.1
> chore: release

- .github/workflows/automatic-release.yml
- dangerfile.ts
> chore: Fetch tags before publishing

- src/compounds/product-table/CHANGELOG.md
- src/compounds/product-table/package.json
- src/compounds/product-table/src/components/data-auto.tsx
- src/elements/hero/CHANGELOG.md
- src/elements/hero/package.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
Fix missing key on ProductTableDataAuto
> fix: issue with key missing on ProductTableDataAuto

- src/compounds/product-table/CHANGELOG.md
- src/compounds/product-table/package.json
- src/compounds/product-table/src/components/cell-base.tsx
- src/compounds/product-table/src/components/cell-content.tsx
- src/compounds/product-table/src/components/row.tsx
- src/compounds/product-table/src/stories.tsx
- src/themes/bankrate/CHANGELOG.md
- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
This fixes the errors that occur in the console due to things missing from the code
> fix: product table console errors

- .github/workflows/automatic-release.yml
> chore: checkout to master before fetching tags

- src/compounds/interactive-tabs/CHANGELOG.md
- src/compounds/interactive-tabs/package.json
- src/compounds/tabs/CHANGELOG.md
- src/compounds/tabs/package.json
- src/elements/card/CHANGELOG.md
- src/elements/card/package.json
- src/elements/category/CHANGELOG.md
- src/elements/category/package.json
- src/layout/flex-grid/CHANGELOG.md
- src/layout/flex-grid/package.json
- src/layout/flex-grid/src/index.tsx
This adds the missing key on flex-grid
> fix: missing key on flex-grid

- .github/workflows/automatic-release.yml
> chore: remove lerna bootstrap from ci

- .github/workflows/automatic-release.yml
> chore: test conventional PR message

- .github/workflows/automatic-release.yml
This flag bypasses prompts from lerna when publishing.
> Add --yes flag to lerna ci

- .github/workflows/automatic-release.yml
> chore: add user information to auto release

- src/elements/icon/src/error.tsx
- src/elements/icon/src/index.tsx
- src/elements/icon/src/stories.tsx
> Add error icon

- package.json
- src/themes/bankrate/theme.json
- src/themes/journey/theme.json
- src/themes/money/theme.json
- src/themes/save-on-energy/theme.json
- src/themes/uswitch-rebrand/theme.json
- src/themes/uswitch/theme.json
This enforces prettier (which we already use for tsx? files) on JSON files too.
> chore: enforce prettier for JSON files

- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
This is some fixes to existing components on money
> fix: money button padding and input element shadow

- src/elements/hero/CHANGELOG.md
- src/elements/hero/package.json
- src/elements/hero/src/index.tsx
- src/themes/bankrate/CHANGELOG.md
- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
- src/themes/journey/CHANGELOG.md
- src/themes/journey/package.json
- src/themes/journey/theme.json
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/save-on-energy/CHANGELOG.md
- src/themes/save-on-energy/package.json
- src/themes/save-on-energy/theme.json
Add form and rich text block panel styling to theme migration
> feat: add form and rich text block panel styling to theme migration

- src/elements/loading-spinner/CHANGELOG.md
- src/elements/loading-spinner/package.json
- src/elements/loading-spinner/src/styles.ts
> chore: spinner update

- src/themes/save-on-energy/theme.json
- [x ] Component library change: storybook / webpack / etc
> feat: add header theme to soe

- src/themes/broadband-deals/.npmrc
- src/themes/broadband-deals/index.js
- src/themes/broadband-deals/package.json
- src/themes/broadband-deals/theme.json
> feat: Add bbdeals theme

- src/themes/broadband-deals/package.json
> Make package public

- src/compounds/side-nav/CHANGELOG.md
- src/compounds/side-nav/package.json
- src/compounds/side-nav/src/index.tsx
- src/themes/broadband-deals/CHANGELOG.md
- src/themes/broadband-deals/package.json
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/save-on-energy/CHANGELOG.md
- src/themes/save-on-energy/package.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Fix issue where the sidenav is broken on uswitch
> fix: issue with broken side nav on uswitch

- src/elements/simple-input/CHANGELOG.md
- src/elements/simple-input/package.json
- src/elements/simple-input/src/index.tsx
- src/elements/simple-input/src/stories.tsx
- src/themes/bankrate/CHANGELOG.md
- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
- src/themes/journey/CHANGELOG.md
- src/themes/journey/package.json
- src/themes/journey/theme.json
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/save-on-energy/CHANGELOG.md
- src/themes/save-on-energy/package.json
- src/themes/save-on-energy/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Add optional prefix to SimpleInput component
money:
uswitch:
> simple input prefix

- .storybook/preview-head.html
- src/elements/card/src/stories.tsx
- src/themes/broadband-deals/theme.json
> feat: update card for bbdeals

- src/elements/simple-input/CHANGELOG.md
- src/elements/simple-input/package.json
- src/themes/bankrate/CHANGELOG.md
- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
- src/themes/broadband-deals/CHANGELOG.md
- src/themes/broadband-deals/package.json
- src/themes/broadband-deals/theme.json
- src/themes/journey/CHANGELOG.md
- src/themes/journey/package.json
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/save-on-energy/CHANGELOG.md
- src/themes/save-on-energy/package.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
also add some upadtes that I got from running lerna verison
> theme warnings case

- src/themes/broadband-deals/CHANGELOG.md
- src/themes/broadband-deals/package.json
- src/themes/broadband-deals/theme.json
> fix: bbdeals font size base

- src/elements/button/src/index.tsx
> fix: inverse props to test lerna automatic publish

- src/elements/list/CHANGELOG.md
- src/elements/list/package.json
- src/elements/list/src/index.tsx
- src/elements/list/src/stories.tsx
- src/themes/bankrate/CHANGELOG.md
- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
- src/themes/broadband-deals/CHANGELOG.md
- src/themes/broadband-deals/package.json
- src/themes/broadband-deals/theme.json
- src/themes/journey/CHANGELOG.md
- src/themes/journey/package.json
- src/themes/journey/theme.json
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/save-on-energy/CHANGELOG.md
- src/themes/save-on-energy/package.json
- src/themes/save-on-energy/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Added variant for list component to render items as a checklist
> feat: add checklist variant to list

- README.md
> docs: Revert docs to pre semantic versioning

- src/themes/bankrate/CHANGELOG.md
- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
- src/themes/journey/CHANGELOG.md
- src/themes/journey/package.json
- src/themes/journey/theme.json
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/save-on-energy/CHANGELOG.md
- src/themes/save-on-energy/package.json
- src/themes/save-on-energy/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
* Update form and button styling for calculator variant
* Add calculator modal styling
> Calculator UI

- src/compounds/sponsored-product/CHANGELOG.md
- src/compounds/sponsored-product/package.json
- src/compounds/sponsored-product/src/index.tsx
> Fix sponsored products

- src/elements/card/CHANGELOG.md
- src/elements/card/package.json
- src/elements/card/src/index.tsx
- src/elements/card/src/stories.tsx
- src/themes/broadband-deals/CHANGELOG.md
- src/themes/broadband-deals/package.json
- src/themes/broadband-deals/theme.json
Card component adjustments for consumer review card.
Also added hero bottom image overflow value for bbdeals theme.
> feat: add header content children prop

- src/elements/card/CHANGELOG.md
- src/elements/card/package.json
- src/elements/card/src/index.tsx
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
fix spacing and layouts and other things for leafeon
theme fixes
> fix: various theme fixes for leafeon

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> uswitch theme fixes

- src/elements/list/CHANGELOG.md
- src/elements/list/package.json
- src/elements/list/src/index.tsx
- src/elements/list/src/stories.tsx
> begin refactor

- src/themes/broadband-deals/CHANGELOG.md
- src/themes/broadband-deals/package.json
- src/themes/broadband-deals/theme.json
logo collection theming for bbdeals
> logo collection

- src/elements/card/CHANGELOG.md
- src/elements/card/package.json
- src/elements/card/src/index.tsx
- src/elements/card/src/stories.tsx
- src/elements/list/CHANGELOG.md
- src/elements/list/package.json
- src/themes/bankrate/CHANGELOG.md
- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
- src/themes/broadband-deals/CHANGELOG.md
- src/themes/broadband-deals/package.json
- src/themes/broadband-deals/theme.json
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/save-on-energy/CHANGELOG.md
- src/themes/save-on-energy/package.json
- src/themes/save-on-energy/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Extended car interface so it can be used as a featured card.
Added responsive variant to themes.
Added featured variant to broadband deals theme.
> Featured card

- src/elements/card/src/stories.tsx
- src/themes/broadband-deals/theme.json
Added theme for assurance bar (bbdeals-theme)
> feat: added theme for assurance-bar

- src/elements/card/src/stories.tsx
- src/themes/broadband-deals/theme.json
Collection Module and Star Rating Component design for Broadband Deals Review Page 
#Screenshoots
> Review page styling

- src/elements/card/CHANGELOG.md
- src/elements/card/package.json
- src/elements/card/src/index.tsx
- src/elements/card/src/stories.tsx
> fix: remove horizontal prop from card

- src/themes/bankrate/CHANGELOG.md
- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
- src/themes/journey/CHANGELOG.md
- src/themes/journey/package.json
- src/themes/journey/theme.json
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/save-on-energy/CHANGELOG.md
- src/themes/save-on-energy/package.json
- src/themes/save-on-energy/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Remove autofill and number input type styling for SimpleInput component
BEFORE:
> SimpleInput Autofill

- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
> add simple-radio to money theme

- src/elements/pagination/src/index.tsx
- src/elements/pagination/src/stories.tsx
- src/themes/broadband-deals/theme.json
Designed pagination component to match design for bbdeals theme
> Pagination

- src/elements/card/src/index.tsx
- src/elements/card/src/stories.tsx
- src/themes/broadband-deals/theme.json
**Implemented assurance bar variant for card**
trustyle 
on demo homepage 
------------------------------------------------------------------------------------------------------------------------------------------
**Featured card design**
on page 
on page - hover 
------------------------------------------------------------------------------------------------------------------------------------------
**Body/p tag text styling fixes**
on page 
------------------------------------------------------------------------------------------------------------------------------------------
**Pros and cons icons**
------------------------------------------------------------------------------------------------------------------------------------------
> Bbdeals visual qa

- src/elements/hero/src/index.tsx
- src/themes/broadband-deals/theme.json
> Align breadcrumbs to header

- src/themes/broadband-deals/theme.json
> feat: update rich-text-mod styling

- src/themes/broadband-deals/theme.json
Title colour and hover state applied to the base variant
> fix: card title color and hover state

- src/elements/card/src/index.tsx
- src/themes/broadband-deals/theme.json
> fix: change card superscript HTML structure

- src/elements/tile-input/CHANGELOG.md
- src/elements/tile-input/package.json
- src/elements/tile-input/src/styles.ts
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Match designs for tile inputs on uswitch
- [ X] Component maintenance: improvement / bug fix / etc
> Update tile input styles

- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
> feat: add form styles for multi section panels

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Fix accordion text colour which was being set to white
- [X ] Component maintenance: improvement / bug fix / etc
> Fix accordion text colour

- src/elements/card/CHANGELOG.md
- src/elements/card/package.json
- src/elements/card/src/index.tsx
> feat: image props for card

- src/themes/uswitch/theme.json
> feat: update uswitch them h3 size

- src/compounds/interactive-tabs/CHANGELOG.md
- src/compounds/interactive-tabs/package.json
- src/compounds/tabs/CHANGELOG.md
- src/compounds/tabs/package.json
- src/elements/card/CHANGELOG.md
- src/elements/card/package.json
- src/elements/category/CHANGELOG.md
- src/elements/category/package.json
- src/layout/flex-grid/CHANGELOG.md
- src/layout/flex-grid/package.json
- src/layout/flex-grid/src/index.tsx
> feat: update flex-grid Container to accept responsive (array) values for cols and span

- src/elements/simple-input/CHANGELOG.md
- src/elements/simple-input/package.json
- src/elements/simple-input/src/index.tsx
remove props being spread to the input
> fix: remove props being spread to input

- src/elements/simple-input/CHANGELOG.md
- src/elements/simple-input/package.json
- src/elements/simple-input/src/index.tsx
> Simple input props

- src/compounds/product-table/CHANGELOG.md
- src/compounds/product-table/package.json
- src/compounds/product-table/src/components/addon-accordion.tsx
- src/compounds/product-table/src/components/rowWrapper.tsx
- src/compounds/side-nav/CHANGELOG.md
- src/compounds/side-nav/package.json
- src/elements/accordion/CHANGELOG.md
- src/elements/accordion/package.json
- src/elements/accordion/src/index.tsx
- src/elements/embedded-video/CHANGELOG.md
- src/elements/embedded-video/package.json
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
Temporary fix for accordions in product tables
> fix: Stop accordion from propagating click events to product table

- src/compounds/product-table/CHANGELOG.md
- src/compounds/product-table/package.json
- src/compounds/product-table/src/components/rowWrapper.tsx
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
> fix: section margin and target check times

- src/elements/card/CHANGELOG.md
- src/elements/card/package.json
- src/elements/card/src/index.tsx
Pass sx from props to card root element
> Card props fix

- src/elements/card/CHANGELOG.md
- src/elements/card/package.json
- src/elements/card/src/index.tsx
> revert card sx forward

- src/themes/bankrate/CHANGELOG.md
- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
> feat: add logo collection to bankrate theme

- src/compounds/product-table/CHANGELOG.md
- src/compounds/product-table/package.json
- src/compounds/product-table/src/components/cell-secondary.tsx
Also applies alignment fixes to secondary cells (on desktop)
> fix: alignment for secondary cells too

- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
> feat: money product table font size

- package-lock.json
- src/elements/awards-tag/src/index.tsx
- src/elements/awards-tag/src/stories.tsx
- src/themes/uswitch/theme.json
> feat: add `inline` prop to AwardsTag

- package-lock.json
package-lock.json was outdated
> fix: build

- src/elements/hero/CHANGELOG.md
- src/elements/hero/package.json
- src/elements/hero/src/index.tsx
- src/elements/hero/src/stories.tsx
Adds ability to pass a custom BG color to Trustyle Hero Component. 
Adds ability to not display FgImage on Tablet. 
> Update trustyle hero

- src/themes/uswitch/theme.json
> fix: remove gap between tabs and hairline

- src/compounds/sponsored-product-rate-table/CHANGELOG.md
- src/compounds/sponsored-product-rate-table/package.json
- src/elements/button/CHANGELOG.md
- src/elements/button/package.json
- src/elements/button/src/index.tsx
- src/elements/button/src/stories.tsx
Added icon to button
Removed console.log from stories
button 1) hero with afterIcon="arrow"
button 2) hero.centered 
> feat: added arrows and centered button

- src/compounds/sponsored-product-rate-table/CHANGELOG.md
- src/compounds/sponsored-product-rate-table/package.json
- src/elements/button/CHANGELOG.md
- src/elements/button/package.json
- src/elements/hero/CHANGELOG.md
- src/elements/hero/package.json
- src/elements/hero/src/index.tsx
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
Removes Img element from DOM if prop `fgImage` is not provided. 
> fix: hero image elements are hidden if fgImage is not provided.

- src/compounds/sponsored-product-rate-table/CHANGELOG.md
- src/compounds/sponsored-product-rate-table/package.json
- src/elements/button/CHANGELOG.md
- src/elements/button/package.json
- src/elements/hero/CHANGELOG.md
- src/elements/hero/package.json
- src/themes/bankrate/CHANGELOG.md
- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
> feat: add styles for zoopla landing page buttons

- src/compounds/interactive-tabs/CHANGELOG.md
- src/compounds/interactive-tabs/package.json
- src/compounds/tabs/CHANGELOG.md
- src/compounds/tabs/package.json
- src/elements/card/CHANGELOG.md
- src/elements/card/package.json
- src/elements/category/CHANGELOG.md
- src/elements/category/package.json
- src/layout/flex-grid/CHANGELOG.md
- src/layout/flex-grid/package.json
- src/layout/flex-grid/src/index.tsx
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
Removes margin bottom if grid is inside a hero
> feat: remove margin bottom if grid is inside a hero

- src/compounds/interactive-tabs/CHANGELOG.md
- src/compounds/interactive-tabs/package.json
- src/compounds/tabs/CHANGELOG.md
- src/compounds/tabs/package.json
- src/elements/card/CHANGELOG.md
- src/elements/card/package.json
- src/elements/category/CHANGELOG.md
- src/elements/category/package.json
- src/layout/flex-grid/CHANGELOG.md
- src/layout/flex-grid/package.json
- src/layout/flex-grid/src/index.tsx
- src/themes/bankrate/CHANGELOG.md
- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Adds a class name to flex grid container for external CSS targeting
> feat: add classname to flex grid container

- src/themes/bankrate/CHANGELOG.md
- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
> feat: style br list

- src/themes/bankrate/theme.json
- src/themes/uswitch/theme.json
Added this rich text block variant
> feat: centered rich text primary panel block

- src/elements/button/package.json
- src/elements/button/src/index.tsx
> fix: fixed broken import

- src/compounds/sponsored-product/CHANGELOG.md
- src/compounds/sponsored-product/package.json
- src/compounds/sponsored-product/src/index.tsx
- src/compounds/sponsored-product/src/stories.tsx
Removes anchor tag that wraps Sponsored product.
Made some changes to styling if a product isn't provider.
> Update sponsored product

- src/compounds/sponsored-product/CHANGELOG.md
- src/compounds/sponsored-product/package.json
- src/compounds/sponsored-product/src/index.tsx
- src/compounds/sponsored-product/src/stories.tsx
adds ability to pass props to info-block and usp tag within sponsored product compound. 
> Updates to elements within Sponsored Products.

- src/compounds/ad-banner/CHANGELOG.md
- src/compounds/ad-banner/package.json
- src/compounds/ad-banner/src/index.tsx
- src/compounds/ad-banner/src/stories.tsx
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Updates to ad banner compound:
- Position background image on desktop view to the right
- Make background image appear behind other content
- Mobiles view same as mobiles view 
- Update story background image link
> Adbanner updates

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> Landingpage tweaks

- src/themes/bankrate/CHANGELOG.md
- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
> feat: add marging to landing page logo

- src/themes/bankrate/CHANGELOG.md
- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
to make cookie banners work (maybe)
> fix: tentative hack to add base padding to bankrate buttons

- package-lock.json
- package.json
Add missing storybook-deployer npm package to package.json so that running `npm run deploy-storybook` deploys storybook to github pages
> feat: add storybook-deployer library to package.json

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Add content-hero-module styling to uswitch theme
> feat: add content-hero-module styling to uswitch theme

- src/compounds/sponsored-product-rate-table/CHANGELOG.md
- src/compounds/sponsored-product-rate-table/package.json
- src/compounds/sponsored-product-rate-table/src/index.tsx
- src/compounds/sponsored-product-rate-table/src/stories.tsx
- src/compounds/sponsored-product/CHANGELOG.md
- src/compounds/sponsored-product/package.json
- src/elements/primary-info-block/CHANGELOG.md
- src/elements/primary-info-block/package.json
- src/elements/primary-info-block/src/index.tsx
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
Removing the wrapping anchor to make it easier to use across products.
Allows passing a custom CTA text
> feat: P4 Remove wrapping anchor; add border hover; allow for custom CTA

- axe-tests.runner.js
- src/elements/embedded-video/src/index.tsx
> fix: set iframe title in EmbeddedVideo

- src/themes/broadband-deals/CHANGELOG.md
- src/themes/broadband-deals/package.json
- src/themes/broadband-deals/theme.json
> merge bbdeals theme back into trustyle

- src/elements/icon/src/index.tsx
- src/elements/icon/src/star-half-filled.tsx
- src/elements/icon/src/stories.tsx
> fix: add half filled star icon

- src/compounds/product-table/CHANGELOG.md
- src/compounds/product-table/package.json
- src/compounds/product-table/src/components/cell-cta.tsx
- src/compounds/product-table/src/components/row.tsx
- src/compounds/product-table/src/stories.tsx
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
Additional product table redesign changes
> fix: styling changes for product table redesign

- src/compounds/product-table/CHANGELOG.md
- src/compounds/product-table/package.json
- src/compounds/product-table/src/components/addon-footer.tsx
- src/compounds/product-table/src/components/addon-info.tsx
- src/compounds/product-table/src/components/data-auto.tsx
- src/compounds/product-table/src/components/data-text-subscript.tsx
- src/compounds/product-table/src/components/header-image.tsx
- src/compounds/product-table/src/components/header.tsx
- src/compounds/product-table/src/components/row.tsx
- src/compounds/product-table/src/stories.tsx
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Additional product table redesign changes
* add data auto format functionality for text with subscript
* adjust spacing
* move border left to outer div so it is the same height for all cells (excluding CTA)
* update addon font 
> Additional product table redesign changes

- src/compounds/interactive-tabs/CHANGELOG.md
- src/compounds/interactive-tabs/package.json
- src/compounds/tabs/CHANGELOG.md
- src/compounds/tabs/package.json
- src/elements/card/CHANGELOG.md
- src/elements/card/package.json
- src/elements/category/CHANGELOG.md
- src/elements/category/package.json
- src/elements/hero-with-background-image/CHANGELOG.md
- src/elements/hero-with-background-image/package.json
- src/layout/flex-grid/CHANGELOG.md
- src/layout/flex-grid/package.json
- src/layout/flex-grid/src/index.tsx
- src/themes/save-on-energy/CHANGELOG.md
- src/themes/save-on-energy/package.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> feat: add ordering to product table

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> Adjust ordering

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> feat: add simple dropdown to uswitch theme

- src/compounds/product-table/CHANGELOG.md
- src/compounds/product-table/package.json
- src/compounds/product-table/src/components/addon-footer.tsx
- src/compounds/product-table/src/components/addon-info.tsx
- src/compounds/product-table/src/components/row.tsx
- src/compounds/product-table/src/components/rowWrapper.tsx
- src/compounds/product-table/src/stories.tsx
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
> feat: product table redesign changes v3

- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
> fix: provider logo maxHeight

- src/compounds/product-table/CHANGELOG.md
- src/compounds/product-table/package.json
- src/compounds/product-table/src/components/row.tsx
Adjusted from 0.7 to 0.5 after talking to design
> fix: Adjust disabled product opacity

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> form styles

- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> Multi step calculator styles

- src/elements/author-profile/CHANGELOG.md
- src/elements/author-profile/package.json
- src/elements/author-profile/src/index.tsx
> Allow styles to be overwritten

- src/compounds/side-nav/CHANGELOG.md
- src/compounds/side-nav/package.json
- src/compounds/sponsored-product-rate-table/CHANGELOG.md
- src/compounds/sponsored-product-rate-table/package.json
- src/compounds/sponsored-product/CHANGELOG.md
- src/compounds/sponsored-product/package.json
- src/elements/accordion/CHANGELOG.md
- src/elements/accordion/package.json
- src/elements/accordion/src/index.tsx
- src/elements/call-out/CHANGELOG.md
- src/elements/call-out/package.json
- src/elements/embedded-video/CHANGELOG.md
- src/elements/embedded-video/package.json
- src/elements/primary-info-block/CHANGELOG.md
- src/elements/primary-info-block/package.json
- src/elements/toggle-switch/CHANGELOG.md
- src/elements/toggle-switch/package.json
- src/utils/palette/CHANGELOG.md
- src/utils/palette/package.json
- src/utils/palette/src/index.tsx
> accordion takes text color from palette

- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
Theme change to update styling for Pension form
> Update styling for Pension form

- src/compounds/product-table/CHANGELOG.md
- src/compounds/product-table/package.json
- src/compounds/product-table/src/components/cell-image.tsx
- src/compounds/product-table/src/components/data-text-subscript.tsx
- src/compounds/product-table/src/components/header-image.tsx
- src/compounds/product-table/src/components/row.tsx
- src/compounds/product-table/src/stories.tsx
- src/compounds/side-nav/CHANGELOG.md
- src/compounds/side-nav/package.json
- src/elements/accordion/CHANGELOG.md
- src/elements/accordion/package.json
- src/elements/accordion/src/index.tsx
- src/elements/embedded-video/CHANGELOG.md
- src/elements/embedded-video/package.json
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Update product table redesign on mobile (Money only) to match legacy design
> Fix/product table redesign - money mobile match legacy design

- src/compounds/sponsored-product-rate-table/CHANGELOG.md
- src/compounds/sponsored-product-rate-table/package.json
- src/compounds/sponsored-product-rate-table/src/index.tsx
- src/compounds/sponsored-product-rate-table/src/stories.tsx
> fix: adding custom backgroundColor for sponsored product rate

- src/compounds/product-table/CHANGELOG.md
- src/compounds/product-table/package.json
- src/compounds/product-table/src/components/cell-image.tsx
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
Fix problems with cellImage sizing in eevee-components
> fix: refactor cellImage variant

- src/elements/hero/CHANGELOG.md
- src/elements/hero/package.json
> Fix palette version

- src/elements/button-link/package.json
- src/elements/button-link/src/index.tsx
> fix: add icons support for button link

- src/elements/simple-input/CHANGELOG.md
- src/elements/simple-input/package.json
- src/elements/simple-input/src/index.tsx
- src/elements/simple-input/src/stories.tsx
- src/themes/bankrate/CHANGELOG.md
- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
- src/themes/journey/CHANGELOG.md
- src/themes/journey/package.json
- src/themes/journey/theme.json
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/save-on-energy/CHANGELOG.md
- src/themes/save-on-energy/package.json
- src/themes/save-on-energy/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Add optional small input field
> SimpleInput optional size

- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Move calculator styling to themes
> move calculator styling to themes

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> merge leafeon theme back into trustyle

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> chore: adds a max width to form input on desktop

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Adds styling for eligibility drop down on uswitch tables
> Style table accordian on uswitch

- src/compounds/product-table/CHANGELOG.md
- src/compounds/product-table/package.json
- src/compounds/product-table/src/components/cell-base.tsx
- src/compounds/product-table/src/components/cell-content.tsx
- src/compounds/product-table/src/components/cell-cta.tsx
- src/compounds/product-table/src/components/cell-secondary.tsx
- src/compounds/product-table/src/components/row.tsx
- src/compounds/product-table/src/generics.ts
- src/compounds/product-table/src/stories.tsx
- src/compounds/sponsored-product-rate-table/CHANGELOG.md
- src/compounds/sponsored-product-rate-table/package.json
- src/elements/button/CHANGELOG.md
- src/elements/button/package.json
- src/elements/button/src/index.tsx
> product table can force mobile layout with card prop

- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
add max width to Icon Tile img when in vertical mode
> add max width to icon tile img when in virtical mode

- src/themes/money/theme.json
> Stying for multi-step form submit section

- src/compounds/product-table/CHANGELOG.md
- src/compounds/product-table/package.json
- src/compounds/product-table/src/components/data-value.tsx
> use force mobile on data value

- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
Styles for the form error state after a failed API call
> feat: form error state

- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
Left text align for form error state
> Form error state

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Card noImage and provider variants added.
Add carousel styling.
> Transactional page changes

- src/compounds/product-table/CHANGELOG.md
- src/compounds/product-table/package.json
- src/elements/author-profile/CHANGELOG.md
- src/elements/author-profile/package.json
- src/elements/author-profile/src/index.tsx
- src/elements/author-profile/src/stories.tsx
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
Add socials href target option
> fix: add socials href target option

- src/compounds/product-table/CHANGELOG.md
- src/compounds/product-table/package.json
- src/compounds/product-table/src/components/header-image.tsx
- src/compounds/product-table/src/generics.ts
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> product table fixes

- src/compounds/legacy-product-table/.npmignore
- src/compounds/legacy-product-table/.npmrc
- src/compounds/legacy-product-table/CHANGELOG.md
- src/compounds/legacy-product-table/package.json
- src/compounds/legacy-product-table/src/index.tsx
- src/compounds/legacy-product-table/src/stories.tsx
New legacy product table component to match the original Money design
> Feat: legacy product table

- src/compounds/sponsored-product/CHANGELOG.md
- src/compounds/sponsored-product/package.json
- src/compounds/sponsored-product/src/index.tsx
- src/compounds/sponsored-product/src/stories.tsx
Enables ability to pass in individual styling for sponsored product usps. 
> feat: allow usps to pass in individual styling.

- src/compounds/legacy-product-table/CHANGELOG.md
- src/compounds/legacy-product-table/package.json
- src/compounds/legacy-product-table/src/index.tsx
- src/compounds/legacy-product-table/src/rowWrapper.tsx
- src/compounds/legacy-product-table/src/stories.tsx
Add link for CTA and optional clickableRow functionality for legacy product table
> Fix/legacy product table CTA and clickableRow

- src/compounds/legacy-product-table/CHANGELOG.md
- src/compounds/legacy-product-table/package.json
- src/compounds/legacy-product-table/src/index.tsx
> fix: update legacy product table checkmark

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> Center calc btn

- src/compounds/product-table/CHANGELOG.md
- src/compounds/product-table/package.json
- src/compounds/product-table/src/components/cell-base.tsx
- src/compounds/product-table/src/components/cell-cta.tsx
- src/compounds/product-table/src/components/cell-secondary.tsx
- src/compounds/product-table/src/components/row.tsx
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
- fix undefined breakpoint issue in product tables
- center cta on tablet
> pt tablet fix

- src/themes/uswitch/theme.json
Styling changes for provider pages
> feat: style provider pages

- src/compounds/legacy-product-table/CHANGELOG.md
- src/compounds/legacy-product-table/package.json
- src/compounds/legacy-product-table/src/index.tsx
- src/compounds/legacy-product-table/src/rowWrapper.tsx
> feat: add onClick prop to clickableRow on legacy product table

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
- more calc styling
- couple more calc style tweaks
> calc styles

- src/themes/uswitch/theme.json
Styling fixes for:
- provider, noImage and vertical card variants stylings
- module spacings
- provider card variant link over entire component
> fix: transactional page feedback

- src/elements/icon/package.json
> fix: icon version bump

- src/compounds/side-nav/CHANGELOG.md
- src/compounds/side-nav/package.json
- src/compounds/sponsored-product-rate-table/CHANGELOG.md
- src/compounds/sponsored-product-rate-table/package.json
- src/compounds/sponsored-product/CHANGELOG.md
- src/compounds/sponsored-product/package.json
- src/elements/accordion/CHANGELOG.md
- src/elements/accordion/package.json
- src/elements/call-out/CHANGELOG.md
- src/elements/call-out/package.json
- src/elements/embedded-video/CHANGELOG.md
- src/elements/embedded-video/package.json
- src/elements/hero/CHANGELOG.md
- src/elements/hero/package.json
- src/elements/primary-info-block/CHANGELOG.md
- src/elements/primary-info-block/package.json
- src/elements/read-more-card/CHANGELOG.md
- src/elements/read-more-card/package.json
- src/elements/toggle-switch/CHANGELOG.md
- src/elements/toggle-switch/package.json
- src/themes/bankrate/CHANGELOG.md
- src/themes/bankrate/package.json
- src/utils/palette/CHANGELOG.md
- src/utils/palette/package.json
- src/utils/palette/src/index.tsx
> fix: Swap palette classname & SX props for more specificity on parent

- src/themes/bankrate/CHANGELOG.md
- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
Responsive card variant styling
> fix: update responsive card variant

- src/compounds/article-intro/CHANGELOG.md
- src/compounds/article-intro/package.json
- src/compounds/article-intro/src/index.tsx
- src/compounds/article-intro/src/stories.tsx
- src/elements/author/CHANGELOG.md
- src/elements/author/package.json
- src/elements/author/src/index.tsx
Update the article intro and author components with the new Palette logic (the headings can either display the chosen textColor or headingColor)
> Update article intro

- src/themes/bankrate/CHANGELOG.md
- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
Card background set to transparent
Remove hover effect from horizontal variant
> fix: card background update

- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
Fixes car insurance spacing issue
> fix: form section spacing

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Fixes padding top/bottom for content in hero. 
> fix: changes padding for hero in uswitch theme to array.

- src/compounds/ad-banner/CHANGELOG.md
- src/compounds/ad-banner/package.json
- src/compounds/hero-card/CHANGELOG.md
- src/compounds/hero-card/package.json
- src/compounds/legacy-product-table/CHANGELOG.md
- src/compounds/legacy-product-table/package.json
- src/compounds/legacy-product-table/src/index.tsx
- src/compounds/legacy-product-table/src/stories.tsx
- src/compounds/sponsored-product-rate-table/CHANGELOG.md
- src/compounds/sponsored-product-rate-table/package.json
- src/compounds/sponsored-product/CHANGELOG.md
- src/compounds/sponsored-product/package.json
- src/elements/button-link/CHANGELOG.md
- src/elements/button-link/package.json
- src/elements/button-link/src/index.tsx
- src/elements/button/CHANGELOG.md
- src/elements/button/package.json
- src/elements/button/src/index.tsx
- src/elements/cta/CHANGELOG.md
- src/elements/cta/package.json
Allow CTA to be rendred as a button for clickable rows
> feat: disable the link on clickable rows

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> updates styles for category-guides-module

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> Remove bottom margin from H2

- src/compounds/legacy-product-table/CHANGELOG.md
- src/compounds/legacy-product-table/package.json
> fix: duplicate icons

- package-lock.json
- package.json
> fix: the lerna publis step

- src/compounds/product-table/CHANGELOG.md
- src/compounds/product-table/package.json
- src/compounds/product-table/src/components/cell-content.tsx
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
- style card variant cell content
- style cta for card variant
> cell content text

- src/themes/uswitch/theme.json
Accordion title font size update
> fix: accordion heading font size

- src/themes/bankrate/CHANGELOG.md
- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
align responsive card text
category guides module mobile layout
> Guides feedback

- src/themes/uswitch/theme.json
Carousel paddings and margins update
> fix: carousel margin and padding update

- src/elements/simple-input/CHANGELOG.md
- src/elements/simple-input/package.json
- src/elements/simple-input/src/index.tsx
- src/elements/simple-input/src/stories.tsx
Allows inputs to be uppercase depending on the schema
> fix: uppercase on text inputs

- src/elements/drop-down/CHANGELOG.md
- src/elements/drop-down/package.json
- src/elements/drop-down/src/index.tsx
Add onClick prop to DropDown component
> feat: add onClick to dropdown component

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
- refactor calc styles into default
- refactor of calculator styles
- add marging to container
> zoopla calc redux

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
- fix mobile styles for zpg calc
- chore: release
> fix mobile calc

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
- tweak margin on calculator
- calc padding tweaks
- better positioning on mobile
- label padding
> zpg v2 tweaks

- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
Show title of the section form when active and the field description
> feat: form field description and section title

- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
> fix: form default variant

- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
> fix: default form styles

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> fix: lead capture form styling

- src/elements/hero/CHANGELOG.md
- src/elements/hero/package.json
- src/elements/hero/src/index.tsx
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Updated hero elements so it can accept custom variants, currently only "provider" enabled.
> CI Provider Hero

- src/compounds/product-table/CHANGELOG.md
- src/compounds/product-table/package.json
- src/compounds/product-table/src/components/data-value.tsx
- src/compounds/product-table/src/components/header.tsx
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
- change cta font size
- max width on calc
- add min height to header image
- remove pl on card variant
- make values bold and support text normal weight
- add no wrap to mortgage table
> zpg final tweaks

- src/compounds/product-table/CHANGELOG.md
- src/compounds/product-table/package.json
- src/compounds/product-table/src/components/header.tsx
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
- remove cta padding
- only have min height on desktop
> zpg mobile

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Add info card variant styling.
> feat: add info card variant styling

- src/elements/accordion/src/stories.tsx
Lots of stories are missing from the accordion which has a lot of variants, so added them all
> fix: add all stories to the accordion

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
- remove mb on mobile calc
- calc title styles
> calc mob padding

- src/compounds/legacy-product-table/CHANGELOG.md
- src/compounds/legacy-product-table/package.json
- src/compounds/legacy-product-table/src/index.tsx
> Remove desktop implementation of eligibility

- src/elements/author-profile/CHANGELOG.md
- src/elements/author-profile/package.json
- src/elements/author-profile/src/index.tsx
- src/elements/author-profile/src/stories.tsx
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
Changed styling of the Author profile element for Money, including left and centered variants.
Changed bio field type for the Author profile element to allow passing both strings and React elements (allowing formatted bio)
> Author profile money theme

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Pros and cons component styling
> fix: pros and cons list styling

- src/compounds/legacy-product-table/CHANGELOG.md
- src/compounds/legacy-product-table/package.json
- src/compounds/legacy-product-table/src/index.tsx
- src/compounds/legacy-product-table/src/stories.tsx
- src/themes/bankrate/CHANGELOG.md
- src/themes/bankrate/package.json
Ref: https://app.asana.com/0/1199920669936537/1199920669936562
Smallest phone:
Desktop:
Mobile without badge:
Desktop without badge:
> Add legacy product table badge support

- src/compounds/legacy-product-table/CHANGELOG.md
- src/compounds/legacy-product-table/package.json
- src/compounds/product-table/CHANGELOG.md
- src/compounds/product-table/package.json
- src/themes/bankrate/CHANGELOG.md
- src/themes/bankrate/package.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> fix: pros and cons margins update

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
- style journey radio
- make journey funnel look like energys
- more journey styles
> journey styles

- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
> fix: pros and cons styling

- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
Ref: https://app.asana.com/0/1183943778484274/1199932432066804
Pension enquiry form: https://money-core-preview.external.usw.co/pensions/pension-enquiry.htm
Completed forms shouldn't be opaic and heading font should be Nunito.
> Pensions form tweaks

- src/themes/bankrate/CHANGELOG.md
- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
Pros and cons variant styling update due to design update
> fix: implement updated design for bankrate

- src/elements/pagination/CHANGELOG.md
- src/elements/pagination/package.json
- src/elements/pagination/src/index.tsx
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
Fix for transparent select options on some browsers.
> fix: hidden select options in pagination

- src/compounds/product-table/CHANGELOG.md
- src/compounds/product-table/package.json
- src/compounds/product-table/src/components/row.tsx
- src/themes/bankrate/CHANGELOG.md
- src/themes/bankrate/package.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
> remove hardcoded styles

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> Fix: filters being always stuck in open state

- src/themes/bankrate/CHANGELOG.md
- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
Fixed spacing between rich bio in author profile and social icons.
> fix: author profile rich bio p formatting

- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
Specifies font size for headline so it doesn't get overridden
> specify hero ad headline font sizing

- src/compounds/advert/CHANGELOG.md
- src/compounds/advert/package.json
- src/compounds/advert/src/index.tsx
- src/compounds/advert/src/stories.tsx
Minor tweaks to the ad to make it work better on mobile
> fix: some minor ad tweaks

- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
Ensure all rich text with icon variants have `alignItems: center`
> fix: alignItems center

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Add button journey card variant hover styling
> Add journey card hover styling

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
- style tweaks for journey
- description text match design '
> journey tweaks

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Edits spacing around base lead capture variant
> fix: Modified spacing for base variant

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> update journey card font weight

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Center align label and field on calculator 
> chore: center align label and form field on calculator

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> remove position relative on journey wrapper

- src/themes/uswitch/theme.json
App download module grey background with image left variant
> App download module

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> update hero variant styles for sponsored-by-tag

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> Hero link style

- src/compounds/legacy-product-table/CHANGELOG.md
- src/compounds/legacy-product-table/package.json
- src/compounds/legacy-product-table/src/index.tsx
- src/compounds/legacy-product-table/src/stories.tsx
Make content an array instead of a string.
> fix: update legacy product table content to be an array

- src/compounds/legacy-product-table/CHANGELOG.md
- src/compounds/legacy-product-table/package.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> fix: filters on uswitch

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Update download module styling for ev-server
> fix: implement app download backgroundImageLeft variant

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Add heading styling for journey form, including sectionName and sectionDescription
> feat: add heading styling for journey form

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Add `solid` variant to card in uswitch theme
> add solid card variant to theme

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> additional affordability calculator styles

- src/compounds/advert/CHANGELOG.md
- src/compounds/advert/package.json
- src/compounds/advert/src/index.tsx
> comment to publish

- src/compounds/legacy-product-table/CHANGELOG.md
- src/compounds/legacy-product-table/package.json
- src/compounds/legacy-product-table/src/index.tsx
Designs:
Before:
After:
fs-core-money before:
fs-core-money after:
> Fix: align table cells

- src/compounds/billboard/.npmignore
- src/compounds/billboard/.npmrc
- src/compounds/billboard/CHANGELOG.md
- src/compounds/billboard/package.json
- src/compounds/billboard/src/index.tsx
- src/compounds/billboard/src/stories.tsx
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> Billboard component

- src/elements/card/CHANGELOG.md
- src/elements/card/package.json
- src/elements/card/src/index.tsx
Add optional button prop to journey card
> add button child to journey card

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> add journey-card background and solid variant article line height

- .github/workflows/publish.yml
This PR attempts to publish packages to Github's registry through Github actions.
The current flow of publishing packages to npm is not changed.
> chore: Publish to github

- src/compounds/legacy-product-table/CHANGELOG.md
- src/compounds/legacy-product-table/package.json
- src/compounds/legacy-product-table/src/index.tsx
- src/compounds/legacy-product-table/src/stories.tsx
> fix: disabled more info

- src/compounds/legacy-product-table/CHANGELOG.md
- src/compounds/legacy-product-table/package.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Update form and article styles on affordability calculator
> Update form and article styles on affordability calculator

- src/compounds/billboard/src/index.tsx
- src/themes/money/theme.json
- src/themes/uswitch/theme.json
> fix: changed spacing and font color

- src/compounds/billboard/CHANGELOG.md
- src/compounds/billboard/package.json
- src/compounds/billboard/src/index.tsx
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> fix: restyled width and color for primary slot

- src/elements/card/CHANGELOG.md
- src/elements/card/package.json
- src/elements/card/src/index.tsx
remove target blank on journey buttons
> remove target blank on journey buttons

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
remove title hover on journey card
> remove title hover on journey card

- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
> feat: simple form variant

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> update journey-card width

- src/compounds/phone-number-modal/.npmignore
- src/compounds/phone-number-modal/.npmrc
- src/compounds/phone-number-modal/CHANGELOG.md
- src/compounds/phone-number-modal/package.json
- src/compounds/phone-number-modal/src/index.tsx
- src/compounds/phone-number-modal/src/stories.tsx
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> add phone number modal

- src/compounds/legacy-product-table/CHANGELOG.md
- src/compounds/legacy-product-table/package.json
- src/compounds/legacy-product-table/src/index.tsx
- src/compounds/legacy-product-table/src/row-wrapper.tsx
- src/compounds/phone-number-modal/CHANGELOG.md
- src/compounds/phone-number-modal/package.json
- src/compounds/phone-number-modal/src/index.tsx
- src/compounds/phone-number-modal/src/stories.tsx
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
-Click handlers for link and modal are separated as onLinkClick and onRowClick
-Style fixes for phone number modal
> Update product table row clicks

- src/compounds/side-nav/src/index.tsx
- src/elements/simple-input/src/index.tsx
Fix console warnings (such as `Warning: Received 'true' for a non-boolean attribute 'uppercase'.`)
> Fix: console warnings

- src/compounds/billboard/CHANGELOG.md
- src/compounds/billboard/package.json
- src/compounds/billboard/src/index.tsx
- src/compounds/side-nav/CHANGELOG.md
- src/compounds/side-nav/package.json
- src/elements/simple-input/CHANGELOG.md
- src/elements/simple-input/package.json
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> fix: spacing issues

- src/compounds/phone-number-modal/src/index.tsx
> fix: width and height issue of logo

- src/compounds/ad-banner/CHANGELOG.md
- src/compounds/ad-banner/package.json
- src/compounds/hero-card/CHANGELOG.md
- src/compounds/hero-card/package.json
- src/compounds/legacy-product-table/CHANGELOG.md
- src/compounds/legacy-product-table/package.json
- src/compounds/sponsored-product-rate-table/CHANGELOG.md
- src/compounds/sponsored-product-rate-table/package.json
- src/compounds/sponsored-product/CHANGELOG.md
- src/compounds/sponsored-product/package.json
- src/elements/button-link/CHANGELOG.md
- src/elements/button-link/package.json
- src/elements/button-link/src/index.tsx
- src/elements/card/CHANGELOG.md
- src/elements/card/package.json
- src/elements/cta/CHANGELOG.md
- src/elements/cta/package.json
Allow button links to track interactions
> Track interaction button link

- src/compounds/side-nav/CHANGELOG.md
- src/compounds/side-nav/package.json
- src/compounds/side-nav/src/index.tsx
> add onClick to side nav links

- src/compounds/ad-banner/CHANGELOG.md
- src/compounds/ad-banner/package.json
- src/compounds/hero-card/CHANGELOG.md
- src/compounds/hero-card/package.json
- src/compounds/legacy-product-table/CHANGELOG.md
- src/compounds/legacy-product-table/package.json
- src/compounds/sponsored-product-rate-table/CHANGELOG.md
- src/compounds/sponsored-product-rate-table/package.json
- src/compounds/sponsored-product/CHANGELOG.md
- src/compounds/sponsored-product/package.json
- src/elements/button-link/CHANGELOG.md
- src/elements/button-link/package.json
- src/elements/button-link/src/index.tsx
- src/elements/card/CHANGELOG.md
- src/elements/card/package.json
- src/elements/card/src/index.tsx
- src/elements/cta/CHANGELOG.md
- src/elements/cta/package.json
- src/elements/imgix-image/src/index.tsx
> Track card

- src/elements/list/src/stories.tsx
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
This allows lists in areas of text that are centred without it being buggy
> feat: allow centered bullets

- src/elements/drop-down/src/index.tsx
- src/themes/money/theme.json
> Fix: sort and filter product table button sizes

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> update description styles on journey form

- src/themes/money/theme.json
> Fix: mobile calculator styling

- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
fix journey description font size
> fix journey description font size

- src/compounds/billboard/CHANGELOG.md
- src/compounds/billboard/package.json
- src/compounds/billboard/src/index.tsx
- src/elements/table/CHANGELOG.md
- src/elements/table/package.json
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
The layout for tablets is changed
**Before**
**After**
> fix: change tablet layout

- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Ref to this comment: https://rv-u.slack.com/archives/C01N3BXEFUL/p1622731382064700?thread_ts=1622631683.017700&cid=C01N3BXEFUL
**Before**
**After**
> fix: set mb of text to 0 when there is just text

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
This is styling on uswitch for simple form
> feat: simple form on uswitch

- src/compounds/billboard/CHANGELOG.md
- src/compounds/billboard/package.json
- src/compounds/billboard/src/index.tsx
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
https://app.asana.com/0/1199990867992543/1200442047248308
https://app.asana.com/0/1199990867992543/1200446088865295
**Before**
**After**
> fix: tablet issues and primarySlot CTA

- src/compounds/sponsored-product/CHANGELOG.md
- src/compounds/sponsored-product/package.json
- src/elements/fieldset/CHANGELOG.md
- src/elements/fieldset/package.json
- src/elements/tile-input/CHANGELOG.md
- src/elements/tile-input/package.json
- src/layout/grid/CHANGELOG.md
- src/layout/grid/package.json
- src/themes/bankrate/CHANGELOG.md
- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> fix themes

- src/compounds/social-sharing/CHANGELOG.md
- src/compounds/social-sharing/package.json
- src/compounds/social-sharing/src/index.tsx
> fix: dedupe twitter prepopulated text

- src/elements/funnel-progress/CHANGELOG.md
- src/elements/funnel-progress/package.json
- src/elements/funnel-progress/src/index.tsx
- src/elements/funnel-progress/src/stories.tsx
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Add percentage variant to funnel progress bar
> Percentage progress bar

- src/elements/card/CHANGELOG.md
- src/elements/card/package.json
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
> Version bump for card-with-date

- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
Money style for `assurance-text` variant of `RichTextBlock`
> feat: caveat box on money

- src/compounds/legacy-product-table/CHANGELOG.md
- src/compounds/legacy-product-table/package.json
- src/compounds/legacy-product-table/src/index.tsx
- src/compounds/legacy-product-table/src/stories.tsx
- src/compounds/product-table/CHANGELOG.md
- src/compounds/product-table/package.json
- src/compounds/product-table/src/components/data-percentage.tsx
- src/compounds/product-table/src/index.tsx
- src/compounds/product-table/src/stories.tsx
> feat: add circular percentage bar to the tables

- src/compounds/legacy-product-table/CHANGELOG.md
- src/compounds/legacy-product-table/package.json
- src/compounds/product-table/CHANGELOG.md
- src/compounds/product-table/package.json
- src/elements/circular-percentage-bar/CHANGELOG.md
- src/elements/circular-percentage-bar/package.json
- src/elements/circular-percentage-bar/src/index.tsx
- src/elements/circular-percentage-bar/src/stories.tsx
**Desktop**
**Tablet**
**Mobile**
> fix: add different alignments for different devices

- src/compounds/product-table/CHANGELOG.md
- src/compounds/product-table/package.json
- src/compounds/product-table/src/components/cell-secondary.tsx
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Styles were breaking with the new `spark` integration, this resolves the bugs that came from the new theme-ui version.
Desktop:
Mobile:
> Fix: variant array bug from new theme-ui version

- src/compounds/legacy-product-table/CHANGELOG.md
- src/compounds/legacy-product-table/package.json
- src/compounds/legacy-product-table/src/index.tsx
There are no visual changes. Changed the type of the banner's badge prop
> fix: badge prop of the preapproved banner

- src/compounds/product-table/CHANGELOG.md
- src/compounds/product-table/package.json
- src/compounds/product-table/src/components/header-banner.tsx
> fix: font size

- src/compounds/legacy-product-table/CHANGELOG.md
- src/compounds/legacy-product-table/package.json
- src/compounds/legacy-product-table/src/index.tsx
Do not render a paragraph if the chunk is null
The other part of the solution is in this pr:
https://github.com/uswitch/fs-core/pull/700
> fix: more information text

- src/compounds/legacy-product-table/CHANGELOG.md
- src/compounds/legacy-product-table/package.json
- src/compounds/legacy-product-table/src/index.tsx
> fix: do not render empty values

- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
Styling for the error message at the bottom: 
> calculator error result style

- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
> Mortgages broker form

- src/themes/money/theme.json
> add collection layout carousel to money theme

- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- force grey background
- chore: release
> grey box fix

- src/compounds/billboard/CHANGELOG.md
- src/compounds/billboard/package.json
- src/compounds/billboard/src/index.tsx
- src/compounds/billboard/src/stories.tsx
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Related ticket: https://rvu.atlassian.net/secure/RapidBoard.jspa?rapidView=80&projectKey=MONEY&modal=detail&selectedIssue=MONEY-103
> feat: add image support to billboard

- src/themes/money/theme.json
- src/themes/uswitch/theme.json
Added Money and Uswitch styles needed to style Spark accordion according to the existing visual style
> feat: spark accordion

- src/elements/wireframe-cell/.npmignore
- src/elements/wireframe-cell/.npmrc
- src/elements/wireframe-cell/CHANGELOG.md
- src/elements/wireframe-cell/package.json
- src/elements/wireframe-cell/src/index.tsx
- src/elements/wireframe-cell/src/stories.tsx
- src/elements/wireframe-cell/src/wireframe-animation.ts
Ticket: https://rvu.atlassian.net/secure/RapidBoard.jspa?rapidView=80&projectKey=MONEY&modal=detail&selectedIssue=MONEY-146&quickFilter=147
A shareable wireframe cell element to build new loading state for product tables
**Animation:**
https://user-images.githubusercontent.com/20357064/128881185-b38c4cb5-b4ae-4330-89a8-5bca98f09e6e.mov
> feat:wireframe cell element with loading animation

- src/elements/wireframe-cell/CHANGELOG.md
- src/elements/wireframe-cell/package.json
- src/elements/wireframe-cell/src/stories.tsx
- src/elements/wireframe-cell/src/wireframe-animation.ts
related merged pr: https://github.com/uswitch/trustyle/pull/1288
> fix: animation slide and make it slower

- src/compounds/legacy-product-table/CHANGELOG.md
- src/compounds/legacy-product-table/package.json
- src/compounds/legacy-product-table/src/index.tsx
- src/compounds/legacy-product-table/src/stories.tsx
Ticket:https://rvu.atlassian.net/secure/RapidBoard.jspa?rapidView=80&projectKey=MONEY&modal=detail&selectedIssue=MONEY-146&quickFilter=147
**Wireframe**
**Other Examples**
To show they still work fine
> feat: add new loading design to the legacy pt

- src/themes/bankrate/CHANGELOG.md
- src/themes/bankrate/package.json
- src/themes/bankrate/theme.json
- src/themes/broadband-deals/CHANGELOG.md
- src/themes/broadband-deals/package.json
- src/themes/broadband-deals/theme.json
- src/themes/journey/CHANGELOG.md
- src/themes/journey/package.json
- src/themes/journey/theme.json
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/save-on-energy/CHANGELOG.md
- src/themes/save-on-energy/package.json
- src/themes/save-on-energy/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> background inital so we never have a blue one

- src/compounds/information-panel/.npmignore
- src/compounds/information-panel/.npmrc
- src/compounds/information-panel/CHANGELOG.md
- src/compounds/information-panel/package.json
- src/compounds/information-panel/src/index.tsx
- src/compounds/information-panel/src/stories.tsx
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
**Ticket:** https://rvu.atlassian.net/browse/MONEY-169
**Current Legacy Product Table**
**New component-Money**
**New component-Uswitch**
> feat: add information panel component

- src/compounds/sponsored-product/CHANGELOG.md
- src/compounds/sponsored-product/package.json
- src/elements/fieldset/CHANGELOG.md
- src/elements/fieldset/package.json
- src/elements/tile-input/CHANGELOG.md
- src/elements/tile-input/package.json
- src/layout/grid/CHANGELOG.md
- src/layout/grid/package.json
- src/layout/grid/src/index.tsx
> fix: add `className` to `grid` props

- src/compounds/legacy-product-table/CHANGELOG.md
- src/compounds/legacy-product-table/package.json
- src/compounds/legacy-product-table/src/index.tsx
- src/compounds/legacy-product-table/src/stories.tsx
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
**Ticket:** https://rvu.atlassian.net/browse/MONEY-227
> feat: add secondary cta to legacy pt

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Added styles for address lookup to uSwitch theme
> update: address lookup styles

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Adds styles for the read more module.
> feat: add read more module styles

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
- wrapper around clickout links
- add tile wrapper for clickout links
> clo wrapper

- src/compounds/billboard/CHANGELOG.md
- src/compounds/billboard/package.json
- src/compounds/billboard/src/index.tsx
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
> billboard height fix

- src/compounds/billboard/CHANGELOG.md
- src/compounds/billboard/package.json
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
> add style for expired modal

- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
> callout icon styling fix

- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- title full width
- padding left on input
> tweak calc

- src/compounds/billboard/CHANGELOG.md
- src/compounds/billboard/package.json
- src/compounds/billboard/src/index.tsx
**Related pr:** https://github.com/uswitch/trustyle/pull/1341
Small changes to render navigation dropdown correctly. 
No visual changes on billboard as Percy confirmed
> fix: styling necessary for navigation dropdown

- src/themes/uswitch/theme.json
Adds styles for postcode form:
> feat: add postcode styles

- src/compounds/billboard/CHANGELOG.md
- src/compounds/billboard/package.json
- src/compounds/billboard/src/index.tsx
- src/compounds/navigation-dropdown/CHANGELOG.md
- src/compounds/navigation-dropdown/package.json
- src/compounds/navigation-dropdown/src/index.tsx
- src/compounds/navigation-dropdown/src/stories.tsx
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
- Style fixes for both billboard and navigation dropdown to fix bugs in fs-core 
- Cloning the children part changed due to changed incoming contentful data
> fix: style tweaks and bug fixes

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> update form styling on uswitch

- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
fix: fixed calculators forms and inputs
before:
after:
> fix: fixed calculators forms and inputs

- src/compounds/navigation-dropdown/CHANGELOG.md
- src/compounds/navigation-dropdown/package.json
- src/compounds/navigation-dropdown/src/index.tsx
- src/compounds/navigation-dropdown/src/stories.tsx
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Ticket: https://rvu.atlassian.net/browse/MONEY-383
> feat: add support for buttons to nav dropdown

- src/compounds/legacy-product-table/CHANGELOG.md
- src/compounds/legacy-product-table/package.json
- src/compounds/legacy-product-table/src/index.tsx
Ticket: https://rvu.atlassian.net/browse/MONEY-366
Before:
After:
> Fix: credit card image alignment

- src/compounds/legacy-product-table/CHANGELOG.md
- src/compounds/legacy-product-table/package.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> fix journey height on mobile

- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> fix: visual bugs on safari

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> adds styling for uswitch credit cards calculator

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
- add onboarding theme
- onboarding styles
> onboarding

- src/compounds/product-table/CHANGELOG.md
- src/compounds/product-table/package.json
- src/compounds/product-table/src/components/cell-content.tsx
- src/compounds/product-table/src/components/data-percentage.tsx
- src/compounds/product-table/src/stories.tsx
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Ticket: https://rvu.atlassian.net/browse/MONEY-530
> fix: changed color and alignment

- src/compounds/navigation-dropdown/CHANGELOG.md
- src/compounds/navigation-dropdown/package.json
- src/compounds/navigation-dropdown/src/index.tsx
- src/themes/money/CHANGELOG.md
- src/themes/money/package.json
- src/themes/money/theme.json
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Ticket: https://rvu.atlassian.net/browse/MONEY-527
> fix: label spacing

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> fix uswitch hero ad text

- src/compounds/advert/CHANGELOG.md
- src/compounds/advert/package.json
- src/compounds/advert/src/index.tsx
- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
> Allow editing of colour of icon in hero ad

- src/themes/uswitch/CHANGELOG.md
- src/themes/uswitch/package.json
- src/themes/uswitch/theme.json
Add styling for uswitch hero ad badge:
> Uswitch Hero Ad Badge
