uswitch/trustyle

src/elements/button/src/styles.ts, src/styles/src/typography.ts
It's possible to achieve something similar by shrinking the lineHeight, but then you also need to be careful about the size of the icons you pass in. It's less dependent on the consumer to just set the height of the button. I can't think of any situation where we would need two rows in a button, so I don't foresee any problems. 
Note: it's 50px with the base font-size. Because it uses pxToRem, it'll still scale if the user has increased their font size.
=> Set button height to 50

src/elements/radio-group/src/stories.tsx
If you import from `radio-input/` it imports from `lib/` because that's what the package.json points to. That means that you have to rebuild to see chages in storybook. Importing from src loads it on every file save.
=> Import from src

src/elements/button/src/index.tsx, src/elements/button/src/stories.tsx, src/elements/button/src/styles.ts
Adds a third style of button for the 'Edit Info' and 'Filter' buttons on the results page.
=> Button: add 'outline' variant

package-lock.json, package.json, src/elements/input/package-lock.json, src/elements/input/package.json, src/elements/input/src/index.tsx
On Android, there is a behaviour where the keyboard may sometimes open ON TOP of a focused input. This effect fixes the problem by calling scrollIntoView on a window resize event - this event is fired when the keyboard opens and pushes up the viewport.
=> Input: useScrollIntoView effect to ensure keyboard does not hide input on Android

src/elements/side-drawer/src/index.tsx, tsconfig.json
The Input component cannot currently be imported into `energy-journey` because of the way it imports `lodash.throttle`. This PR enables the `esModuleInterop` flag, thanks @peterhorne .
=> TS: turn on esModuleInterop flag so that Input can be imported into energy-journey

src/elements/button/src/stories.tsx, src/elements/button/src/styles.ts, src/elements/drop-down/src/stories.tsx, src/elements/drop-down/src/styles.ts, src/elements/frozen-input/src/styles.ts, src/styles/src/inputs.ts
1. Adds a focus border to buttons
2. Removes the default FF dashed-border around the buttons' text
3. Removes the FF dashed-border around selects' text
4. Adds a focus border around the frozen-input edit button
5. Removes the chrome-mobile orange focus border around drop-downs
I've tested it on most of the major browsers, but you can play with it on https://uswitch.github.io/trustyle/?path=/story/styles-colours--swatches. There is an external Safari bug (default behaviour) where it ignores buttons when tabbing.
=> Focus state

src/styles/src/utils.ts
This means you can see the actual value when hovering over a spacer in
your editor rather than just `number`.
=> Mark spacers as const

src/elements/side-drawer/src/index.tsx, src/elements/side-drawer/src/stories.tsx, src/elements/side-drawer/src/styles.ts
Rather than wrap the triggerElement in a button, the api should allow the consumer to supply any element. The documentation should describe how to use it semantically, but doesn't need to enforce that. 
I'm prevent the default event handler on that click, which means that you can use an `<a>` component. In this scenario, clicking the link will open the modal,  but the user will be able to right-click and open the href in a new window.
=> Drawer trigger

src/elements/input/src/index.tsx
`react-input-mask` (2.0.4) only supports a callback-style `inputRef` prop. It seems like this will be fixed in a later release, but for now we can change `inputRef` to be a callback.
=> Input: ensure masked fields scroll into view

src/elements/button/src/index.tsx, src/elements/button/src/stories.tsx, src/elements/icon/src/index.tsx, src/elements/icon/src/plus.tsx, src/elements/icon/src/stories.tsx
Allows any valid button attributes as props to the button element, which will be applied directly to the button, with the exception of the type prop which works as it did before.
The goal is to have transparent props for any element which is basically just a styled html element.
=> Make button props transparent

src/elements/drop-down/src/index.tsx
we were seeing a console error if we didn't pass a value to onBlur on the dropdown component, looks like because it didn't have a default set up
=> added default value to dropdown onblur

src/elements/drop-down/src/index.tsx, src/elements/drop-down/src/stories.tsx, src/elements/frozen-input/src/index.tsx, src/elements/input/src/index.tsx
When the user clicks on the edit button of a frozen input it should give focus to the element that is unfrozen. This will only happen if a ref to the input is passed and the element is freezable in the first place.
This is currently used by Input and Dropdown components.
=> Focus on the input after it is unfrozen

src/elements/drop-down/src/styles.ts
color was previously set to transparent so that the 'focus-ring' in Firefox does not show up around the text of a Dropdown. But this causes Edge to display the text color as transparent. This PR defines a color for the Dropdown text and introduces a specific override for ::-moz-focusring
=> Add color style to DropDown for Edge

src/layout/grid/src/styles.ts
On IE11, the two columns will be displayed on top of each because IE11 does not take into account the `border-box` layout in its flexbox calculations. This PR subtracts the paddings for IE.
=> Grid column to support IE11

src/elements/checkbox-input/package-lock.json, src/elements/drop-down/package-lock.json, src/elements/drop-down/src/index.tsx, src/elements/fieldset/package-lock.json, src/elements/tile-input/package-lock.json, src/layout/grid/package-lock.json
The ref is not currently available for the select on the initial render, so focus will fail on the featured input. Since the element might not be displayed, we use `useImperativeHandle` to control its behaviour.
=> Dropdown: Ensure focus/scrollIntoView behaviour is available for dropdowns

src/elements/list/list-item.js, src/elements/list/list.js
You can only use default exports with loadable(), apparently
=> fix: make two shortcuts for getting List and ListItem as default exports

src/elements/button/src/index.tsx, src/elements/button/src/stories.tsx, src/elements/list/package-lock.json, src/themes/uswitch/theme.json
* Add type back to Variant. I feel the theme should not be driving the semantics of the button, and having variant typed as a string makes it a little more difficult to use. Think we should discuss this at some point.
* Add `iconPosition` prop to Button. This supports left/right/center aligned icon button formats. (Essentially replaces justifyContent we had before).
* Update theme for reasonable Button styles.
=> Tweak Button for uSwitch

src/styles/src/typography.ts
The latest change to uStyle has introduced unwanted styles for a:visited.
=> Force color for a:visited links

package.json, publish.sh
Currently, we run npm install after lerna version, but before the packages are published. This means that the integrity and version parts of package-lock.json cannot be updated.
This PR ensures that package-lock.json are updated after lerna publish. It copies over the tags to the newly-created commit.
=> Update package-lock.json after lerna publish

.drone.yml
As far as I can tell from the docs, each step runs in series on the code
from the previous step - removing the duplicate steps should speed up
the build.
=> Improve drone build time

babel.config.js, package-lock.json, package.json, src/elements/call-out/src/index.tsx, src/elements/category/src/index.tsx, src/elements/cta/src/index.tsx, src/elements/icon/src/stories.tsx, src/elements/pagination/src/index.tsx
Shouldn't have had to add the optional chaining plugin, but for some reason even though @babel/plugin-typescript is supposed to support the syntax from 7.8.3, it was erroring when building (worked in storybook though)
Spent a bit of time attempting a proper fix, but made no progress and this isn't the worst fix ever 🤷‍♂
=> Upgrade typescript and switch to optional chaining operator

src/elements/accordion/src/index.tsx, src/elements/button/src/index.tsx, src/elements/button/src/stories.tsx, src/themes/money/theme.json, src/themes/uswitch/theme.json
After a conversation with barney, we decided to move variants into a `variants` object under a component.
This is a:
=> Standardise how component variants are structured in themes

.storybook/config.js, .storybook/preview-body.html, src/layout/grid/src/stories.tsx, src/layout/grid/src/styles.ts
we now have 16px padding on the `<Container>`, -8px margin on `<Row>` and 8px padding on `<Column>`
this gives a grid of 16px at either side of the container, and 16px between columns, which is *not* like ustyle which has 15px either side of the container and 15px * 2 = 30px between columns
This is a:
=> fix grid to match designs

src/elements/button-link/src/index.tsx, src/elements/button-link/src/stories.tsx
Button theming was broken by https://github.com/uswitch/trustyle/pull/247, this fixes it
This is a:
=> Fix button link theme after variant change

src/elements/funnel-progress/src/index.tsx, src/themes/journey/theme.json
The 'no progress' case needs to be styled as a special variant, because we want the progress bar to have a minimum-width. This ensures it does not clash with the step icon, while still supporting 0% progress.
This is a:
=> Tweak funnel progress bar styles

.storybook/config.js
The viewport addon was failing to load because the available viewports were changed yesterday but the default wasn't updated - am updating that to fix it :)
=> Fix viewport plugin - was erroring because default didn't exist

src/elements/button-link/src/index.tsx, src/elements/button-link/src/stories.tsx, src/elements/pagination/src/stories.tsx
In apps where we use react-router, we want a Trustyle button link that actually uses Link from react-router. We can use a styled component to achieve this, using it in this way:
```
<ButtonLink
as={Link}
to={href}
onClick={onPlanInfoClick}
variant="secondary"
>
Plan info
</ButtonLink>
```
This is a:
=> Convert ButtonLink into a styled component

src/themes/journey/theme.json
Because the ButtonLink components also take styles from a:hover, the text colour is incorrect. This updates the theme to specify the color for each variant.
This is a:
=> Journey: add :hover colors for ButtonLinks

src/themes/journey/theme.json
The button uses `width: 100%`, but don't use `border-box` in Journey so it's width appears too large in Plan Info.
This is a:
=> Journey: render ButtonLink with box-sizing: border-box

src/elements/breadcrumbs/src/index.tsx, src/elements/breadcrumbs/src/stories.tsx
The breadcrumbs in contentful were all linked to the home breadcrumb so it appeared twice. This change means that it only appears once, but can still be customised.
This is a:
=> Remove duplicate home links when used inside eevee

src/elements/radio-input/src/index.tsx, src/themes/journey/theme.json
Updates radio button theming for journey theme
This is a:
=> Add radio theming for journey

src/elements/tile-input/src/index.tsx, src/elements/tile-input/src/stories.tsx, src/elements/tile-input/src/styles.ts, src/themes/journey/theme.json, src/themes/money/theme.json, src/themes/uswitch/theme.json
Converts TileInput to use theming
This is a:
=> Convert TileInput to use theming

src/elements/global-styles/src/stories.tsx, src/themes/money/theme.json
They were the same size on desktop and mobile - should have been a size smaller on mobile.
=> Made header sizes smaller on mobile

src/elements/button/package.json, src/elements/button/src/index.tsx
Currently the variant prop can only be a child of the button in the theme. This allows it to also take an absolute theme path
=> Allow button to take full variant path

src/themes/money/package.json, src/themes/money/theme.json, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
Add theming for the cookie banner (found in https://github.com/uswitch/recharge-mewtru)
=> added cookie-banner compound to themes

src/themes/journey/theme.json, src/themes/money/theme.json, src/themes/save-on-energy/theme.json, src/themes/uswitch/theme.json
set `"useBodyStyles": false` in all themes
theme-ui doc <https://theme-ui.com/theming#body-styles>
theme-ui applies styles to the `<body>` such as `{"backgroundColor": "background"}` (which comes through as a bluish colour if your theme does not have a colour named "background"
Setting this to false disables this behavior
=> disable trustyle body styles

src/compounds/ad-banner/package.json, src/compounds/ad-banner/src/index.tsx, src/elements/button/package.json, src/elements/card/package.json, src/elements/imgix-image/package.json, src/elements/imgix-image/src/index.tsx
Lazyload shouldn't be a dependency on imgix component but instead on User. 
=> Remove lazyload from imgix

src/compounds/ad-banner/package.json, src/compounds/ad-banner/src/index.tsx, src/elements/button/package.json, src/elements/card/package.json, src/elements/imgix-image/package.json, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
The display flex change wasn't applied in all themes and broke the current usages of the component as it changed the default width.
Better for this to be done where the component is used!
=> Revert breaking change to badge component

src/elements/input/src/index.tsx
Right now Energy Journey is using `tel` as the input type for spend and energy consumption but `number` would be better suited.
For this I've added the `number` type to the possible input types.
=> Added number for input type

src/elements/input/package.json, src/elements/input/src/index.tsx
it seem in Energy Journey Props are only used for a Number input that's used for mpan, mprn, consumption and spend while the InputType is used for another text-input component-element.
In order not to break this dependency it's better to add the type back, even if it is lacking from the Props.
=> # Input type again

src/compounds/sponsored-product-rate-table/package.json, src/compounds/sponsored-product/package.json, src/elements/card/package.json, src/elements/category/package.json, src/elements/primary-info-block/package.json, src/layout/flex-grid/package.json, src/layout/flex-grid/src/index.tsx, src/layout/flex-grid/src/stories.tsx
This will come in handy in places like the collection component where the layout doesn't know how many children it is going to be receiving.
=> Add wildcard support to flex-grid's LayoutFromJson component

src/themes/uswitch/package.json, src/themes/uswitch/theme.json
Removed Helvetica Now fonts from uswitch theme as still waiting for sign off on webfont license. Incident to be raised.
=> Revert fonts

src/compounds/sponsored-product-rate-table/package.json, src/compounds/sponsored-product-rate-table/src/index.tsx, src/compounds/sponsored-product/package.json, src/compounds/sponsored-product/src/index.tsx, src/elements/usp-tag/package.json, src/elements/usp-tag/src/index.tsx, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
Make usp color an optional prop on sponsored product so that can be changed within external projects. Added all system fonts to uswitch theme and made usp tag element use theme fonts. 
=> Usp color fixes

.drone.yml
Looks like there was a bug in the changes yesterday to speed up the build, some packages have been published without being built
lets roll back for now
=> looks like packages were getting published without having been built

src/compounds/product-table/package.json, src/compounds/product-table/src/components/data-value.tsx, src/compounds/product-table/src/generics.ts, src/compounds/product-table/src/stories.tsx
Fix the `numberFormatter` generic function to accept `null` as a unit.
=> Update numberFormatter to accept null as a unit

src/compounds/product-table/package.json, src/compounds/product-table/src/components/cell-base.tsx, src/compounds/product-table/src/components/cell-content.tsx, src/compounds/product-table/src/components/cell-image.tsx, src/compounds/product-table/src/components/row.tsx, src/compounds/product-table/src/stories.tsx, src/themes/money/package.json, src/themes/money/theme.json, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
=> Update product table styling

src/themes/money/theme.json
Add `contentSpan` to `imageModule` in money's theme ahead of changes to
eevee.
https://github.com/uswitch/recharge-eevee/pull/315
=> Add imageModule size to money theme

src/themes/money/package.json, src/themes/money/theme.json
Money Theme updates to support top orientation in callout element
orientation left:
orientation top:
=> Theme updates to support top orientation in callout

src/elements/button/package.json, src/elements/button/src/index.tsx, src/themes/bankrate/package.json, src/themes/bankrate/theme.json, src/themes/money/package.json, src/themes/money/theme.json
- With one line of text, the button height was slightly too small
- Buttons couldn't have more than one line of text
https://app.asana.com/0/1153286245702289/1175415548003665
=> Remove hardcoded button height - was causing bugs

src/themes/bankrate/package.json, src/themes/bankrate/theme.json, src/themes/journey/package.json, src/themes/journey/theme.json, src/themes/money/package.json, src/themes/money/theme.json, src/themes/save-on-energy/package.json, src/themes/save-on-energy/theme.json, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
We don't use user-configurable colour modes and yet theme-ui still tries
to write to localStorage without handling failure cases. This is
impacting a significant number of our customers.
https://theme-ui.com/color-modes/#disable-persisting-color-mode-on-localstorage
=> Disable localStorage for theme-ui

src/elements/call-out/package.json, src/elements/call-out/src/index.tsx
Can't be overridden as is - will re-add spacing in eevee when updating.
=> Remove spacing from call out component

src/elements/category/package.json, src/elements/category/src/index.tsx
The margin bottom was only being overridden on mobile as the margin bottom in a media query was more specific and overriding it.
=> Fix spacing issue in category header

src/themes/bankrate/package.json, src/themes/bankrate/theme.json, src/themes/money/package.json, src/themes/money/theme.json, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
Button variant already prefixes `buttons.variants` so specifying the
fully qualified key in the cookie-banner theme means the styles aren't
loaded. https://github.com/uswitch/trustyle/blob/639e68462a212119755648b8eb746017f84670ed/src/elements/button/src/index.tsx#L60
=> Fix cookie-banner button variants

src/compounds/product-table/package.json, src/compounds/product-table/src/components/cell-image.tsx
Replaces object-fit which doesn't have support on IE11
Before:
After:
=> make product table images work on ie11

src/elements/input/src/index.tsx
Android doesn't always scroll focused elements into view so we manually
do it. The code to handle this was broken in a previous commit.
=> fix: android keyboard focus

src/compounds/product-table/package.json, src/compounds/product-table/src/components/row.tsx
Was broken here when tablet product table tablet breakpoint was shown mobile layout instead of desktop, but IE11 breakpoint wasn't adjusted: https://github.com/uswitch/trustyle/pull/475/files#diff-4d553efec1d2b870ecca128c23369239
=> Fix product table tablet breakpoint in IE11

src/elements/drop-down/package.json, src/elements/drop-down/src/index.tsx, src/elements/drop-down/src/stories.tsx, src/elements/themed-icon/package.json, src/elements/themed-icon/src/index.tsx, src/themes/money/package.json, src/themes/money/theme.json
- Add overlay support to dropdown component
- Make caret icon colour themeable
- Fix bug where themed-icon missing icon didn't have `className` passed through to it
- Couple border-radius changes in money theme
=> Add overlay support to dropdown component (and minor visual changes)

src/elements/toggle-switch/src/index.tsx
Remaining props are passed to input element but type definition didn't
extend input props.
=> Fix typings for ToggleSwitch

lerna.json
As you have to push before running `lerna version`, drone runs on that and so isn't needed on the version commit.
This will speed up the process of getting stuff approved and merged.
=> Skip drone on lerna version commits to speed up time to merge

src/elements/pagination/package.json, src/elements/pagination/src/index.tsx
Current Behaviour:
When you click on the arrow on the right you are taken to the last page
When you click on the arrow on the left you are taken to the first page
Expected Behaviour:
When you click on the arrow on the right you are taken to the next page
When you click on the arrow on the left you are taken to the previous page
=> Fix previous/next pagination buttons

src/elements/icon-tile/src/index.tsx
In the hero on the homepage we have the category tiles however they are quite large, as part of the new homepage design we have decided to slim these down. This is a replacement of the old, larger design.
=> Slim hero category tiles on desktop

src/elements/drop-down/package.json, src/elements/frozen-input/package.json, src/elements/frozen-input/src/index.tsx, src/elements/input/package.json
For some reason this component is throwing an error `Cannot read property 'name' of null` when used in `Dropdown -> Eevee Components -> Eevee`.
I don't know why, because it works in just `Dropdown -> Eevee Components`, and there is definitely a theme in Eevee because other components use it in the exact same way, but this fixes it.
=> fix throwing error if theme is undefined

src/themes/bankrate/theme.json, src/themes/money/theme.json, src/themes/uswitch/theme.json
Category guides model uses `itemsPerRow` to calculate how many columns. This was removed by accident. This PR adds it back to money, uswitch and bankrate
=> Move itemsPerRow to correct position

README.md
Have seen a couple people get blocked by this recently, and a bunch of the bot warnings in #trustyle were from people versioning early and then having to merge in master.
=> Update README with warning about versioning early

src/compounds/interactive-tabs/package.json, src/compounds/side-nav/package.json, src/compounds/sponsored-product-rate-table/package.json, src/compounds/sponsored-product/package.json, src/compounds/testimonial-card/package.json, src/elements/accordion/package.json, src/elements/author-profile/package.json, src/elements/breadcrumbs/package.json, src/elements/bullet-list-highlight/package.json, src/elements/call-out/package.json, src/elements/category/package.json, src/elements/drop-down/package.json, src/elements/embedded-video/package.json, src/elements/frozen-input/package.json, src/elements/icon/package.json, src/elements/icon/src/filled-arrow.tsx, src/elements/icon/src/index.tsx, src/elements/icon/src/stories.tsx, src/elements/input/package.json, src/elements/link-list/package.json, src/elements/link-list/src/index.tsx, src/elements/link-list/src/stories.tsx, src/elements/pagination/package.json, src/elements/read-more-card/package.json, src/elements/side-drawer/package.json, src/themes/money/package.json, src/themes/money/theme.json
Add quick links as a variant to link list. Affects Money theme.
=> Add quick links as variant to link list

src/elements/card/src/index.tsx
Images in cards are not lazyloaded. This commit introduces a `critical`
prop that can be used to enable lazyloading.
=> Add critical prop to Card (for imgix)

src/themes/bankrate/package.json, src/themes/bankrate/theme.json, src/themes/journey/package.json, src/themes/journey/theme.json, src/themes/money/package.json, src/themes/money/theme.json, src/themes/save-on-energy/package.json, src/themes/save-on-energy/theme.json, src/themes/uswitch-rebrand/package.json, src/themes/uswitch-rebrand/theme.json, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
Add styling for the Form (label and button) and Rich Text Block (base and panel-primary variant) to the themes for all brands. Note: Input styling will be on another PR
=> Form and Rich Text Block panel styling to themes

src/elements/drop-down/package.json, src/elements/frozen-input/package.json, src/elements/frozen-input/src/index.tsx, src/elements/input/package.json
In some cases (when used in the sort component) the theme is not defined when the frozen input is server side rendered. Need to look more into this to figure out why, but this is a temporary fix to stop it from breaking.
=> Theme is sometimes undefined in server side rendering - temporary fix

src/themes/uswitch/theme.json
This pull request sets useBodyStyles to false for Uswitch (we already have this for money, bankrate, etc.). This stops styles being applied on the body object - and hence stops theme ui turning the webpage purple.
Not adding a new component. Not really a straightforward way to locally test that this does what we expect, either.
- [ N/A] Includes theme changes for both Uswitch and money
- [ N/A] Work has been tested in multiple browsers
- [ N/A] PR description includes screenshot of change
- [ N/A] If new component, designer has approved screenshot
- [ N/A] If the change will affect other teams, that team knows about this change
- [ N/A] If introducing a new component behaviour, added a story to cover that case.
- [ N/A] If component change, …
=> Set useBodyStyles to false to keep the background non-purple

src/themes/money/theme.json
Changed logo collection width in Money theme. Fixes bug that was causing smaller images to not render.
=> fix: change width in logo collection for money theme

src/elements/hero/CHANGELOG.md, src/elements/hero/package.json, src/elements/hero/src/index.tsx, src/themes/money/CHANGELOG.md, src/themes/money/package.json, src/themes/money/theme.json
Fix styling of hero breadcrumbs for Money
=> fix: hero breadcrumb styling for Money

.github/pull_request_template.md, src/elements/modal/package.json, src/elements/modal/src/index.tsx
The ThemedIcon doesn't currently work, so updating the Modal to use the existing `Icon` component for the timebeing.
~~- [ ] Includes theme changes for both Uswitch and money~~
~~- [ ] PR description includes screenshot of change~~
~~- [ ] If new component, designer has approved screenshot~~
=> Change Modal to use legacy Icon so that close icon works

src/compounds/product-table/CHANGELOG.md, src/compounds/product-table/package.json, src/compounds/product-table/src/components/addon-responsive.tsx
Removes vertical margin from responsive addon, which is about to be implemented for images in eevee-components
Old:
New:
=> fix: removes vertical margin from responsive addon

src/elements/modal/CHANGELOG.md, src/elements/modal/package.json, src/elements/modal/src/index.tsx
Scrolling was enabled on the wrong element. Also ensures momentum scrolling for Safari <= 12.
~~- [ ] PR description includes screenshot of change!~~
~~- [ ] If new component, designer has approved screenshot~~
=> Modal scrolling

src/elements/modal/CHANGELOG.md, src/elements/modal/package.json, src/themes/bankrate/CHANGELOG.md, src/themes/bankrate/package.json, src/themes/money/CHANGELOG.md, src/themes/money/package.json, src/themes/money/theme.json
Fix margin for logo collection to center logos on mobile for Money
=> fix: center margins on logo collection for Money

src/elements/modal/CHANGELOG.md, src/elements/modal/package.json, src/elements/modal/src/index.tsx
If two nested `Modal` are rendered, click events on the background div can propagate up to the parent modal's background div. This makes both modals call `onClose`. (React bubbles events through portals.)
~~- [ ] Includes theme changes for both Uswitch and money~~
~~- [ ] PR description includes screenshot of change~~
~~- [ ] If new component, designer has approved screenshot~~
=> Support nested modals (do not propagate click events on background)

src/elements/loading-spinner/CHANGELOG.md, src/elements/loading-spinner/package.json, src/themes/bankrate/CHANGELOG.md, src/themes/bankrate/package.json, src/themes/bankrate/theme.json, src/themes/journey/CHANGELOG.md, src/themes/journey/package.json, src/themes/journey/theme.json, src/themes/money/CHANGELOG.md, src/themes/money/package.json, src/themes/money/theme.json, src/themes/save-on-energy/CHANGELOG.md, src/themes/save-on-energy/package.json, src/themes/save-on-energy/theme.json, src/themes/uswitch/CHANGELOG.md, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
Added input box-shadow and error/focus/default colors to the themes. No change to existing Input styling, for use in Form Input in eevee.
=> feat: add form input colors and box-shadow to themes

src/elements/list/CHANGELOG.md, src/elements/list/package.json, src/elements/modal/CHANGELOG.md, src/elements/modal/package.json, src/elements/modal/src/index.tsx, src/elements/modal/src/stories.tsx, src/themes/bankrate/CHANGELOG.md, src/themes/bankrate/package.json, src/themes/money/CHANGELOG.md, src/themes/money/package.json, src/themes/save-on-energy/CHANGELOG.md, src/themes/save-on-energy/package.json, src/themes/uswitch/CHANGELOG.md, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
When modals are nested, we want to render only the top-most modal.
Before:
After:
=> For nested modals, only render the top-most modal

src/themes/money/CHANGELOG.md, src/themes/money/package.json, src/themes/money/theme.json
Increase size of powered by logo for Money
=> fix: update money theme to increase powered by logo size

src/themes/uswitch/CHANGELOG.md, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
No other theme except uswitch applies a custom font size globally on the anchor and it breaks stuff such as the breadcrumb
=> fix: breadcrumb sizing

src/elements/simple-input/CHANGELOG.md, src/elements/simple-input/package.json, src/elements/simple-input/src/index.tsx, src/elements/simple-input/src/stories.tsx, src/themes/bankrate/CHANGELOG.md, src/themes/bankrate/package.json, src/themes/bankrate/theme.json, src/themes/journey/CHANGELOG.md, src/themes/journey/package.json, src/themes/journey/theme.json, src/themes/money/CHANGELOG.md, src/themes/money/package.json, src/themes/money/theme.json, src/themes/save-on-energy/CHANGELOG.md, src/themes/save-on-energy/package.json, src/themes/save-on-energy/theme.json, src/themes/uswitch/CHANGELOG.md, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
Add suffix to SimpleInput componet
money:
uswitch:
=> feat: add suffix to simple input component

src/elements/input/src/styles.ts
In some of our themes we don't want a box shadow, this enables you to configure the box shadow to none.
=> Make the box shadow on the input element fully configurable in the theme

src/compounds/side-nav/CHANGELOG.md, src/compounds/side-nav/package.json, src/elements/accordion/CHANGELOG.md, src/elements/accordion/package.json, src/elements/accordion/src/index.tsx, src/elements/embedded-video/CHANGELOG.md, src/elements/embedded-video/package.json, src/elements/input/CHANGELOG.md, src/elements/input/package.json
Fix Accordion component to use values from the correct part of the theme
=> fix: get accordion values from correct part of theme

src/compounds/product-table/CHANGELOG.md, src/compounds/product-table/package.json, src/compounds/product-table/src/components/row.tsx
Fix bug where margin bottom was not added to a clickable row.
AFTER:
BEFORE:
=> fix: clickable row margin

src/compounds/product-table/CHANGELOG.md, src/compounds/product-table/package.json, src/compounds/product-table/src/components/addon-info.tsx, src/compounds/product-table/src/index.tsx, src/compounds/product-table/src/stories.tsx
Adds an info addon to the product table. This addon appears above the footer, to show compliance and other extra info.(The grey text here on the old table):
=> feat: add info addon to product table

src/compounds/product-table/CHANGELOG.md, src/compounds/product-table/package.json, src/compounds/product-table/src/components/cell-content.tsx, src/compounds/product-table/src/components/data-auto.tsx, src/compounds/product-table/src/components/data-value.tsx
- make all columns equal height, which aligns bottom text,  and aligns value text to start
- adds margin to auto formatter, and removes space from custom formatter (as that can be added in if required)
=> Table cell alignment

src/elements/icon-tile/CHANGELOG.md, src/elements/icon-tile/package.json, src/elements/icon-tile/src/index.tsx, src/elements/icon-tile/src/stories.tsx
Add option to vertically align the icon tile on desktop and mobile
=> feat: icon tile vertically align styling

src/themes/uswitch/theme.json
Buttons on interactive tabs have different sizes when active/non-active.
Switching between tabs causes the element to shift down the page
slightly.
=> Fix page movement when using interative tabs

src/compounds/sponsored-product/CHANGELOG.md, src/compounds/sponsored-product/package.json, src/compounds/sponsored-product/src/index.tsx, src/compounds/sponsored-product/src/stories.tsx
If product image isn't provided for sponsored product component. Awards image is shifted to the bottom of the component. 
=> fix: adjust position of award if product img is not provided.

axe-tests.runner.js, src/elements/slide-reveal/src/stories.tsx
Fixes story so we can enable `a11y` check against `SlideReveal`
=> fix: a11y: add alt tag to SlideReveal story

src/elements/embedded-video/CHANGELOG.md, src/elements/embedded-video/package.json, src/themes/uswitch/CHANGELOG.md, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
When hovering a btn link, the text goes dark on dark bg variants.
E.g. Primary and Reversed.
Before
After
=> fix: Fix btn link dark text on dark bg

src/compounds/sponsored-product-rate-table/CHANGELOG.md, src/compounds/sponsored-product-rate-table/package.json, src/compounds/sponsored-product-rate-table/src/index.tsx
Changes info block container from height to minHeight to account for cases where there's a long description, preventing text overlapping USP underneath.
Before
After
=> fix: Change Info block container height to minHeight to prevent overlap

src/compounds/sponsored-product-rate-table/CHANGELOG.md, src/compounds/sponsored-product-rate-table/package.json, src/elements/button/CHANGELOG.md, src/elements/button/package.json, src/elements/button/src/index.tsx, src/elements/button/src/stories.tsx, src/themes/uswitch/CHANGELOG.md, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
Adds true speed variant to button within Uswitch Theme. 
=> feat: add true-speeds theme variant to button.

src/compounds/sponsored-product-rate-table/CHANGELOG.md, src/compounds/sponsored-product-rate-table/package.json, src/compounds/sponsored-product/CHANGELOG.md, src/compounds/sponsored-product/package.json, src/elements/call-out/CHANGELOG.md, src/elements/call-out/package.json, src/elements/primary-info-block/CHANGELOG.md, src/elements/primary-info-block/package.json, src/elements/toggle-switch/CHANGELOG.md, src/elements/toggle-switch/package.json, src/utils/palette/CHANGELOG.md, src/utils/palette/package.json, src/utils/palette/src/index.tsx
BREAKING CHANGE: uses padding and not overflow hidden, this could break things
Uses padding 0.05px rather than overflow:hidden to prevent margin collapse on palettes
I think that this is a better solution as it should not have any side effects (unlike overflow)
=> fix: use small padding to fix margin collapse rather than overflow hidden

src/elements/hero-with-background-image/CHANGELOG.md, src/elements/hero-with-background-image/package.json, src/elements/hero-with-background-image/src/index.tsx, src/elements/hero-with-background-image/src/stories.tsx, src/themes/save-on-energy/CHANGELOG.md, src/themes/save-on-energy/package.json, src/themes/save-on-energy/theme.json
Add image opacity option for hero with background image.
=> fix: hero with bg img opacity option

src/elements/pagination/CHANGELOG.md, src/elements/pagination/package.json, src/elements/pagination/src/index.tsx
Fix for mobile pagination not triggering when END_LENGTH of desktop less than total pages
=> fix: mobile pagination not triggering

src/elements/pagination/CHANGELOG.md, src/elements/pagination/package.json, src/elements/pagination/src/index.tsx
This should fix:
- bug: on Android phones native select wouldn't change the page
- bug: on Mac OS and iOS devices native select wouldn't change to the page if it was first in list
- bug: no last page in select list
- bug: list of numbers and "..." wouldn't update on current page change
- [ xxx ] Component maintenance: improvement / bug fix / etc
=> Pagination select fix

src/elements/pagination/CHANGELOG.md, src/elements/pagination/package.json, src/elements/pagination/src/index.tsx
For some reason if the first render is set to the value of minimized variable it fails to update. Changed it for now.
=> fix: force first render to be for desktop

src/compounds/side-nav/CHANGELOG.md, src/compounds/side-nav/package.json, src/compounds/sponsored-product-rate-table/CHANGELOG.md, src/compounds/sponsored-product-rate-table/package.json, src/compounds/sponsored-product/CHANGELOG.md, src/compounds/sponsored-product/package.json, src/elements/accordion/CHANGELOG.md, src/elements/accordion/package.json, src/elements/embedded-video/CHANGELOG.md, src/elements/embedded-video/package.json, src/elements/sponsored-by-tag/CHANGELOG.md, src/elements/sponsored-by-tag/package.json, src/elements/sponsored-by-tag/src/index.tsx, src/elements/sponsored-by-tag/src/stories.tsx, src/themes/money/CHANGELOG.md, src/themes/money/package.json, src/themes/uswitch/CHANGELOG.md, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
Fixing sponsored tag styling as per https://www.figma.com/file/PAhSkRBmvjcxHWAnxLUYEy/Finance---heroes?node-id=26%3A6
=> fix: uswitch sponsored-by-tag

src/themes/uswitch/CHANGELOG.md, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
Increase margin left for the image in the sponsored by tag
=> fix: margin left to uswitch sponsored by tag image

src/elements/hero/CHANGELOG.md, src/elements/hero/package.json, src/elements/hero/src/index.tsx, src/elements/hero/src/stories.tsx
Allow Hero component background color to be set with a Palette in Contentful
=> feat: allow hero to be styled with palette

src/compounds/product-table/CHANGELOG.md, src/compounds/product-table/package.json, src/compounds/product-table/src/components/rowWrapper.tsx
Fix bug that did not allow buttons to be clicked inside of eligibility criteria section of the product table 
=> fix: allow button to be clicked inside of eligibility criteria

src/compounds/product-table/CHANGELOG.md, src/compounds/product-table/package.json, src/compounds/product-table/src/components/row.tsx, src/compounds/product-table/src/stories.tsx, src/themes/money/CHANGELOG.md, src/themes/money/package.json, src/themes/money/theme.json, src/themes/uswitch/CHANGELOG.md, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
Don't render fourth column on desktop only on redesign if image is in the cell content (used for Money mobile redesign)
Before:
4th column of data not showing
=> fix: fourth column on product tables

dangerfile.ts
As we are not using semantic commits for anything under the hood having them fail the build is OTT
=> Make danger provide message instead of fail for non semantic commits

src/compounds/sponsored-product/CHANGELOG.md, src/compounds/sponsored-product/package.json, src/compounds/sponsored-product/src/index.tsx, src/compounds/sponsored-product/src/stories.tsx
Allows Sponsored Product usps to be styled individually. Meaning that a specifc usp can be given a different color if so desired.
=> feat: usps now array of usps. Means you can pass color for specfic usp.

src/compounds/ad-banner/CHANGELOG.md, src/compounds/ad-banner/package.json, src/compounds/hero-card/CHANGELOG.md, src/compounds/hero-card/package.json, src/compounds/sponsored-product-rate-table/CHANGELOG.md, src/compounds/sponsored-product-rate-table/package.json, src/compounds/sponsored-product/CHANGELOG.md, src/compounds/sponsored-product/package.json, src/compounds/sponsored-product/src/index.tsx, src/elements/button-link/CHANGELOG.md, src/elements/button-link/package.json, src/elements/button-link/src/index.tsx, src/elements/button/CHANGELOG.md, src/elements/button/package.json, src/elements/button/src/index.tsx, src/elements/cta/CHANGELOG.md, src/elements/cta/package.json, src/elements/drop-down/CHANGELOG.md, src/elements/drop-down/package.json, src/elements/frozen-input/CHANGELOG.md, src/elements/frozen-input/package.json, src/elements/frozen-input/src/index.tsx, src/elements/input/CHANGELOG.md, src/elements/input/package.json
BREAKING CHANGE
The `trustyle.icon` package brings all the icons with its default export. This makes bundles really bloated when we're only looking to use one or two icons.
The purpose of this PR is to make some components directly import the icons they need.
=> chore: import specific icons from src to avoid importing all icons

src/compounds/sponsored-product/CHANGELOG.md, src/compounds/sponsored-product/package.json, src/compounds/sponsored-product/src/index.tsx, src/elements/drop-down/CHANGELOG.md, src/elements/drop-down/package.json, src/elements/frozen-input/CHANGELOG.md, src/elements/frozen-input/package.json, src/elements/frozen-input/src/index.tsx, src/elements/input/CHANGELOG.md, src/elements/input/package.json
Previous changes to try importing specific trustyle icons by using the /src/[Icon] relative url didn't actually work outside storybook. For that reason this changes are being reverted.
=> Revert using /src/ import for icons as it breaks packages

src/compounds/legacy-product-table/CHANGELOG.md, src/compounds/legacy-product-table/package.json, src/themes/uswitch/CHANGELOG.md, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
h2 font size and line height update
=> fix: h2 font size and line height update

package-lock.json, package.json, src/compounds/legacy-product-table/CHANGELOG.md, src/compounds/legacy-product-table/package.json, src/compounds/sponsored-product-rate-table/CHANGELOG.md, src/compounds/sponsored-product-rate-table/package.json, src/compounds/sponsored-product-rate-table/src/index.tsx, src/compounds/sponsored-product-rate-table/src/stories.tsx, src/elements/button/CHANGELOG.md, src/elements/button/package.json
Adds flexibility in sponsored product rate table to style specific usps differently. 
=> Enable styling of specific usps in sponsored product rate table

src/compounds/sponsored-product-rate-table/CHANGELOG.md, src/compounds/sponsored-product-rate-table/package.json, src/compounds/sponsored-product/CHANGELOG.md, src/compounds/sponsored-product/package.json, src/elements/sponsored-by-tag/CHANGELOG.md, src/elements/sponsored-by-tag/package.json, src/elements/sponsored-by-tag/src/index.tsx, src/themes/bankrate/CHANGELOG.md, src/themes/bankrate/package.json, src/themes/bankrate/theme.json, src/themes/journey/CHANGELOG.md, src/themes/journey/package.json, src/themes/journey/theme.json, src/themes/save-on-energy/CHANGELOG.md, src/themes/save-on-energy/package.json, src/themes/save-on-energy/theme.json, src/themes/uswitch/CHANGELOG.md, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
The provider image is being loaded with a massive resolution when we only display a max of 92x46.
This ensures that we don't exceed those dimensions and load an image that is appropriate. We were loading a massive image before.
=> fix: Add correct dimensions to provider img

src/compounds/sponsored-product-rate-table/CHANGELOG.md, src/compounds/sponsored-product-rate-table/package.json, src/compounds/sponsored-product/CHANGELOG.md, src/compounds/sponsored-product/package.json, src/elements/sponsored-by-tag/CHANGELOG.md, src/elements/sponsored-by-tag/package.json, src/elements/sponsored-by-tag/src/index.tsx, src/themes/bankrate/CHANGELOG.md, src/themes/bankrate/package.json, src/themes/bankrate/theme.json, src/themes/journey/CHANGELOG.md, src/themes/journey/package.json, src/themes/journey/theme.json, src/themes/save-on-energy/CHANGELOG.md, src/themes/save-on-energy/package.json, src/themes/save-on-energy/theme.json, src/themes/uswitch/CHANGELOG.md, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
Fixes sponsored image aspect ratio on P4's
=> fix: Load the correct sized sponsored img when in portrait

src/compounds/legacy-product-table/CHANGELOG.md, src/compounds/legacy-product-table/package.json, src/compounds/legacy-product-table/src/index.tsx
* Fix bug where mobile eligibility was also showing on desktop
* Fix font colors for data cells
=> fix: legacy product table eligibility bugs and styling 

src/compounds/legacy-product-table/CHANGELOG.md, src/compounds/legacy-product-table/package.json, src/compounds/legacy-product-table/src/index.tsx
Fix bug that rendered empty eligibility criteria, additional information, and footer addons on legacy product table.
AFTER:
BEFORE:
=> fix: legacy product table only render addons in schema

src/elements/button/src/index.tsx, src/elements/sponsored-by-tag/src/stories.tsx, src/themes/money/CHANGELOG.md, src/themes/money/package.json, src/themes/money/theme.json
Ignore the white brackground of the image, that comes from data
=> fix: form sponsored by image size

src/elements/slide-reveal/CHANGELOG.md, src/elements/slide-reveal/package.json, src/elements/slide-reveal/src/index.tsx
- Fixes bug where product table filters are initially open on page load
- Add optional prop to set initial state to false
After (on page load):
Before (on page load): 
=> fix: initial open slide reveal bug

src/compounds/side-nav/CHANGELOG.md, src/compounds/side-nav/package.json, src/elements/accordion/CHANGELOG.md, src/elements/accordion/package.json, src/elements/accordion/src/index.tsx, src/elements/accordion/src/stories.tsx, src/elements/drop-down/src/stories.tsx, src/elements/embedded-video/CHANGELOG.md, src/elements/embedded-video/package.json, src/themes/uswitch/CHANGELOG.md, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
- Add option to pass ref to element to scroll to for reverse accordion on close. At the moment when there is a lot of content within the accordion, when it is closed the user is left in a random spot further down the page which they haven't scrolled to yet. 
- Remove min width from dropdown element. Instead the dropdown can be sized using its container.
https://user-images.githubusercontent.com/21021507/103561738-d97da480-4eb1-11eb-8878-1649a5f8ea2f.mov
=> Accordion scroll

src/compounds/side-nav/CHANGELOG.md, src/compounds/side-nav/package.json, src/elements/accordion/CHANGELOG.md, src/elements/accordion/package.json, src/elements/accordion/src/index.tsx, src/elements/embedded-video/CHANGELOG.md, src/elements/embedded-video/package.json
Add `buttonProps` to Accordion which are passed down to the underlying
button element.
This facilitates nerdalytics integration.
=> feat: add `buttonProps` to accordion

src/themes/uswitch/theme.json
Rich text left variant styling, alignment, mobile margins and font sizes.
=> fix: rich-text-block variants update

src/themes/uswitch/CHANGELOG.md, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
remove margin from h2 and p in image-callout
=> fix: remove margin from h2 and p in image-callout

src/compounds/interactive-tabs/CHANGELOG.md, src/compounds/interactive-tabs/package.json, src/compounds/tabs/CHANGELOG.md, src/compounds/tabs/package.json, src/elements/card/CHANGELOG.md, src/elements/card/package.json, src/elements/category/CHANGELOG.md, src/elements/category/package.json, src/layout/flex-grid/CHANGELOG.md, src/layout/flex-grid/package.json, src/layout/flex-grid/src/index.tsx
Offset would return last member of array if it was equal to 0.
=> fix: offset not working if equal to 0

src/compounds/legacy-product-table/CHANGELOG.md, src/compounds/legacy-product-table/package.json, src/compounds/legacy-product-table/src/index.tsx
Show desktop eligibility on legacy product table even when there is no hydration
=> fix: desktop eligiblity through css

src/elements/category/CHANGELOG.md, src/elements/category/package.json, src/elements/category/src/index.tsx
This will allow hiding on mobile without removing from desktop
=> feat: allow hiding of description on mobile

src/themes/uswitch/CHANGELOG.md, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
Hero variant for rich text block
=> fix: add rich-text-block hero variant

src/elements/category/CHANGELOG.md, src/elements/category/package.json, src/elements/category/src/index.tsx
Don't show info button if hideOnModile is falsy in category heading module
=> fix: don't show info button if hideOnModile is falsy

src/themes/uswitch/CHANGELOG.md, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
Add center shrink variant to rich text block. This variant centres content and also shrink the width of it.
=> fix: rich text block center-shrink variant styling

src/elements/icon/CHANGELOG.md, src/elements/icon/src/bookmark-filled.tsx, src/elements/icon/src/bookmark.tsx, src/elements/icon/src/index.tsx, src/elements/icon/src/stories.tsx, src/elements/save-for-later/CHANGELOG.md, src/elements/save-for-later/package.json, src/elements/save-for-later/src/index.tsx, src/elements/save-for-later/src/stories.tsx
Small component for implementing as save for later component on a product table.
=> Add save for later component and icon

src/themes/uswitch/theme.json
Changed styling of the Author profile element for Uswitch (rebrand), including left and centered variants.
=> fix: updated styling for uswitch theme author profile variants

src/compounds/ad-banner/CHANGELOG.md, src/compounds/ad-banner/package.json, src/compounds/hero-card/CHANGELOG.md, src/compounds/hero-card/package.json, src/compounds/legacy-product-table/CHANGELOG.md, src/compounds/legacy-product-table/package.json, src/compounds/sponsored-product-rate-table/CHANGELOG.md, src/compounds/sponsored-product-rate-table/package.json, src/compounds/sponsored-product/CHANGELOG.md, src/compounds/sponsored-product/package.json, src/elements/button-link/CHANGELOG.md, src/elements/button-link/package.json, src/elements/button-link/src/index.tsx, src/elements/button-link/src/stories.tsx, src/elements/cta/CHANGELOG.md, src/elements/cta/package.json, src/themes/money/theme.json
Add optional before and after icons to button-link
=> Feat: add optional before and after icons to button-link

src/themes/bankrate/CHANGELOG.md, src/themes/bankrate/package.json, src/themes/bankrate/theme.json
Fixed Bankrate theme to allow rich text elements as author profile biography.
=> fix: rich bio field for author profile on bankrate

src/compounds/product-table/CHANGELOG.md, src/compounds/product-table/package.json, src/compounds/product-table/src/components/row.tsx
Ref: https://app.asana.com/0/1199920669936537/1199921369865118
Also tested: http://localhost:3000/mortgages, and works as expected 👍 
=> Fix product rows so they are always 100%

src/themes/money/CHANGELOG.md, src/themes/money/package.json, src/themes/money/theme.json
Changes here: https://github.com/uswitch/trustyle/pull/1072 have caused our radio button styles to no longer work as expected.
Style radio buttons for desktop and mobile.
Mobile:
Desktop:
=> Fix: trustyle radio spacing

src/themes/uswitch/CHANGELOG.md, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
Styles for leadCaptureForm email-capture variant to align left on desktop, add padding, plus make us of grid size value rather than per cent
=> fix: Left align email capture form, use grid value instead of per cent, add margin bottom

src/themes/money/CHANGELOG.md, src/themes/money/package.json, src/themes/money/theme.json
Ref: https://app.asana.com/0/1183943778484274/1199932432066804
Add `36px` spacing below all inputs on mobile.
Add `56px` spacing below all inputs on desktop except last input which is `36px` spacing.
As per design spec here: https://www.notion.so/rvu/Pensions-form-feedback-992d1e4b699d43368d17c83a5d72fd12
Desktop:
Mobile:
=> Feat: form input spacing

src/themes/uswitch/CHANGELOG.md, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
Added styles for hero versions of posctode and care registration capture that also feature email capture.
Once eevee is also updated, this will allow contenful users to add email capture to lead-capture forms 
=> feat: styled postcode/registraion with email variant for all breakpoints

src/themes/money/CHANGELOG.md, src/themes/money/package.json, src/themes/money/theme.json
Styling for `centered` sponsored-by variant.
=> Feat: add centered sponsored-by variant

src/compounds/side-nav/CHANGELOG.md, src/compounds/side-nav/package.json, src/compounds/side-nav/src/index.tsx
Explicit `tabindex` attribute (with the default value of 0) has been added to the link in side nav element to help with the way browsers apply default styles to focused elements.
=> fix: add explicit tabindex to sidenav links

src/compounds/product-table/CHANGELOG.md, src/compounds/product-table/package.json, src/compounds/product-table/src/components/row.tsx, src/compounds/product-table/src/components/rowWrapper.tsx
It's just a callback passed through the row props so it can eventually be called when the link is pressed.
=> feat: add row clickout callback function for usage in segment tracking

src/elements/call-out/CHANGELOG.md, src/elements/call-out/package.json, src/elements/call-out/src/index.tsx
Change this so it overrides bold on uswitch being set to 500
=> fix: issue where the call out doesnt appear to be bold enough

src/themes/money/CHANGELOG.md, src/themes/money/package.json, src/themes/money/theme.json
Add sponsored by variant color to money theme
=> fix: add sponsored by centered variant color to theme

src/themes/money/CHANGELOG.md, src/themes/money/package.json, src/themes/money/theme.json
In https://money.co.uk/pensions/pension-enquiry.htm?tracking=false the dropdown borders aren't behaving as expected for an error state.
The border is being overwritten by `initial`.
This can be fixed by being more specific for each of the borders.
=> fix: be more specic for simple drop down border

src/compounds/legacy-product-table/CHANGELOG.md, src/compounds/legacy-product-table/package.json, src/compounds/legacy-product-table/src/index.tsx, src/compounds/legacy-product-table/src/stories.tsx
This adds support for customising the more info label
=> feat: add custom more info label

src/compounds/sponsored-product-rate-table/CHANGELOG.md, src/compounds/sponsored-product-rate-table/package.json, src/compounds/sponsored-product/CHANGELOG.md, src/compounds/sponsored-product/package.json, src/elements/sponsored-by-tag/CHANGELOG.md, src/elements/sponsored-by-tag/package.json, src/elements/sponsored-by-tag/src/index.tsx
Fixes the alignment of text and logo in sponsored by component
broken version from: 
fixed to: 
=> align sponsored by logo with text

src/compounds/sponsored-product-rate-table/CHANGELOG.md, src/compounds/sponsored-product-rate-table/package.json, src/compounds/sponsored-product/CHANGELOG.md, src/compounds/sponsored-product/package.json, src/elements/sponsored-by-tag/CHANGELOG.md, src/elements/sponsored-by-tag/package.json, src/elements/sponsored-by-tag/src/index.tsx, src/elements/sponsored-by-tag/src/stories.tsx, src/themes/money/CHANGELOG.md, src/themes/money/package.json, src/themes/money/theme.json
Flex breaks the sponsor hero on fs-core like this: 
Changed to inline-flex: 
=> flex fix for sponsored by tag

src/compounds/phone-number-modal/CHANGELOG.md, src/compounds/phone-number-modal/package.json, src/elements/modal/CHANGELOG.md, src/elements/modal/package.json, src/elements/modal/src/index.tsx, src/elements/modal/src/stories.tsx
Allow `backdropBlur` prop to be passed to Modal for blurred background effect. Uses `backdrop-filter` which is currently unsupported by Firefox (planned) & IE
- [X ] Component maintenance: improvement / bug fix / etc
=> Add option to blur backdrop to modal

src/compounds/legacy-product-table/CHANGELOG.md, src/compounds/legacy-product-table/package.json, src/compounds/legacy-product-table/src/index.tsx, src/compounds/side-nav/CHANGELOG.md, src/compounds/side-nav/package.json, src/elements/accordion/CHANGELOG.md, src/elements/accordion/package.json, src/elements/accordion/src/index.tsx, src/elements/embedded-video/CHANGELOG.md, src/elements/embedded-video/package.json, src/themes/bankrate/CHANGELOG.md, src/themes/bankrate/package.json, src/themes/bankrate/theme.json, src/themes/journey/CHANGELOG.md, src/themes/journey/package.json, src/themes/journey/theme.json, src/themes/money/CHANGELOG.md, src/themes/money/package.json, src/themes/money/theme.json, src/themes/save-on-energy/CHANGELOG.md, src/themes/save-on-energy/package.json, src/themes/save-on-energy/theme.json, src/themes/uswitch/CHANGELOG.md, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
Fixes `first-child` and kebab case not supported warnings for money theme and components.
=> Fix: warnings

src/elements/table/CHANGELOG.md, src/elements/table/package.json, src/elements/table/src/index.tsx
Ensure table overflows on mobile.
=> Fix: mobile table overflow

src/themes/money/CHANGELOG.md, src/themes/money/package.json, src/themes/money/theme.json
Fixes spacing issues with form radio buttons.
Before:
After:
=> Fix: radio spacing

src/compounds/social-sharing/CHANGELOG.md, src/compounds/social-sharing/package.json
The publish github action isn't working because the social-sharing package.json is missing the repository key.
This PR solves this. 
=> fix: Adds missing repository key to social-sharing packag.json

src/elements/funnel-progress/CHANGELOG.md, src/elements/funnel-progress/package.json, src/elements/funnel-progress/src/index.tsx, src/themes/uswitch/CHANGELOG.md, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
fix percentage progress bar variant min bar width; display 10% width at start
=> Percentage progress bar min width

src/elements/circular-percentage-bar/.npmignore, src/elements/circular-percentage-bar/.npmrc, src/elements/circular-percentage-bar/CHANGELOG.md, src/elements/circular-percentage-bar/package.json, src/elements/circular-percentage-bar/src/index.tsx, src/elements/circular-percentage-bar/src/percentage-bar-styles.ts, src/elements/circular-percentage-bar/src/stories.tsx, src/themes/money/CHANGELOG.md, src/themes/money/package.json, src/themes/money/theme.json, src/themes/uswitch/CHANGELOG.md, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
Created circle percentage bar that can have different sizes
**Money**
**Uswitch**
=> feat: create circle percentage bar element

src/themes/uswitch/theme.json
Since we created a new header component for Uswitch and it's not a horizontal card anymore, we can revert the changes made to the horizontal card.
**Before**
**After**
=> fix: revert uswitch horizontal card changes

src/elements/circular-percentage-bar/CHANGELOG.md, src/elements/circular-percentage-bar/package.json, src/elements/circular-percentage-bar/src/index.tsx, src/elements/circular-percentage-bar/src/percentage-bar-styles.ts, src/elements/circular-percentage-bar/src/stories.tsx, src/themes/money/CHANGELOG.md, src/themes/money/package.json
Added an alignment prop because of the different requirements of the brands 
=> fix: add align prop to set different alignments

src/compounds/legacy-product-table/CHANGELOG.md, src/compounds/legacy-product-table/package.json, src/compounds/legacy-product-table/src/index.tsx, src/compounds/product-table/CHANGELOG.md, src/compounds/product-table/package.json, src/compounds/product-table/src/components/header-banner.tsx, src/compounds/product-table/src/components/row.tsx, src/themes/money/CHANGELOG.md, src/themes/money/package.json, src/themes/money/theme.json, src/themes/uswitch/CHANGELOG.md, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
=> Feat: add modal to preapproved banner

src/themes/broadband-deals/CHANGELOG.md, src/themes/broadband-deals/package.json, src/themes/broadband-deals/theme.json, src/themes/journey/CHANGELOG.md, src/themes/journey/package.json, src/themes/journey/theme.json, src/themes/money/CHANGELOG.md, src/themes/money/package.json, src/themes/money/theme.json, src/themes/uswitch/CHANGELOG.md, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
The article used to sometimes "jump" to the first heading after navigating to it.
=> Sticky sidenav CLS

src/compounds/legacy-product-table/CHANGELOG.md, src/compounds/legacy-product-table/package.json, src/compounds/legacy-product-table/src/index.tsx, src/compounds/product-table/CHANGELOG.md, src/compounds/product-table/package.json, src/compounds/product-table/src/components/header-banner.tsx
=> fix: change margin top when there is no badge

src/compounds/legacy-product-table/CHANGELOG.md, src/compounds/legacy-product-table/package.json, src/compounds/legacy-product-table/src/index.tsx, src/compounds/legacy-product-table/src/stories.tsx
Show `No results found for this` text if the percentage is not a number
related change: https://github.com/uswitch/fs-core/pull/708
=> fix: show text if the percantage is not a number

src/themes/money/theme.json
Grey-box variant for Rich Text Block for the Money theme
https://www.notion.so/rvu/Grey-box-rich-text-block-variant-on-Money-9be630b1a85946579513d867dba12662
=> feat: grey-box rich text block on money

src/compounds/sponsored-product-rate-table/CHANGELOG.md, src/compounds/sponsored-product-rate-table/package.json, src/compounds/sponsored-product/CHANGELOG.md, src/compounds/sponsored-product/package.json, src/elements/sponsored-by-tag/CHANGELOG.md, src/elements/sponsored-by-tag/package.json, src/elements/sponsored-by-tag/src/index.tsx, src/elements/sponsored-by-tag/src/stories.tsx, src/themes/money/CHANGELOG.md, src/themes/money/package.json, src/themes/money/theme.json, src/themes/uswitch/CHANGELOG.md, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
Ref: https://rvu.atlassian.net/browse/MONEY-91
Adjust size of sponsored by logo.
Before:
After:
=> Fix: max-width for wide sponsored by logos

src/themes/money/theme.json
Adding Assurance Bar Card variation styling to money theme
=> Assurance bar styling for money

src/themes/money/CHANGELOG.md, src/themes/money/package.json, src/themes/money/theme.json
This resolves styling issues on pensions and mortgages form
before: 
after:
=> feat: fix styling on sponsored by on form

src/themes/money/CHANGELOG.md, src/themes/money/package.json, src/themes/money/theme.json
Move styles from eevee-components to trustyle (see this commit: https://github.com/uswitch/eevee-components/pull/292/commits/12dc47ae00ff974e0a335212df00d32884ee2c97)
=> feat: add address-lookup styling - taken from eevee-components

src/themes/uswitch/theme.json
We previously used system fonts on uswitch, and now we are moving to
helvetica now, however we dont yet have a licence for helvetica now.
This commit adds the system fonts back into the font family in the
uswitch theme, it shouldnt make much difference, but it fixes an issue
where some characters were not being rendered correctly as they were
in none of the availble fonts
=> Include system fonts in uswitch font family

src/themes/uswitch/theme.json
Uswitch theme modifications to allow using Image Modules v2 (with image caption) on Uswitch
https://www.notion.so/rvu/Image-captions-on-Uswitch-742019e4e1cc4eef91cf5ffc76c185bc
=> fix: uswitch theme mods for image module

src/compounds/ad-banner/CHANGELOG.md, src/compounds/ad-banner/package.json, src/compounds/hero-card/CHANGELOG.md, src/compounds/hero-card/package.json, src/compounds/legacy-product-table/CHANGELOG.md, src/compounds/legacy-product-table/package.json, src/compounds/sponsored-product-rate-table/CHANGELOG.md, src/compounds/sponsored-product-rate-table/package.json, src/compounds/sponsored-product/CHANGELOG.md, src/compounds/sponsored-product/package.json, src/elements/button-link/CHANGELOG.md, src/elements/button-link/package.json, src/elements/button-link/src/index.tsx, src/elements/card/CHANGELOG.md, src/elements/card/package.json, src/elements/cta/CHANGELOG.md, src/elements/cta/package.json
make the whole btn link the same color inside
https://www.notion.so/rvu/Button-has-grey-background-applied-to-button-text-when-embedded-onto-greybox-rich-text-variant-746381c5b50c49fba8ff63c75b2a0067
=> fix: make the whole btn link the same color inside

src/themes/uswitch/theme.json
Adds styles for lead-capture-form "postcode-secondary" variant.
"postcode-secondary" variant is just styling over postcode-capture-form to be used on guide pages and where necessary.
=> feat: add postcode-secondary styles

src/themes/money/CHANGELOG.md, src/themes/money/package.json, src/themes/money/theme.json
FIx the spacing on input alert
=> fix: input alert spacing incorrect

src/compounds/phone-number-modal/CHANGELOG.md, src/compounds/phone-number-modal/package.json, src/elements/modal/CHANGELOG.md, src/elements/modal/package.json, src/elements/modal/src/index.tsx, src/elements/modal/src/stories.tsx, src/themes/uswitch/CHANGELOG.md, src/themes/uswitch/package.json
The modal currently closes if the user starts to 'click' inside of the modal, and drags their mouse outside. This is easy to do when the modal contains a text input that the user is trying to highlight.
Instead, we keep track of the mousedown and mouseup elements, and do not close if the drag started inside or finished inside of the modal content.
~~- [ ] Includes theme changes for both Uswitch and money~~
~~- [ ] PR description includes screenshot of change~~
~~- [ ] If new component, designer has approved screenshot~~
=> fix: do not close modal if dragging mouse into or out of content

src/compounds/information-panel/CHANGELOG.md, src/compounds/information-panel/package.json, src/compounds/information-panel/src/index.tsx, src/compounds/information-panel/src/stories.tsx, src/compounds/legacy-product-table/CHANGELOG.md, src/compounds/legacy-product-table/package.json
Ticket: https://rvu.atlassian.net/browse/MONEY-376
Here is the two different types of more information text:
=> fix: more information text does not render ul

src/themes/money/CHANGELOG.md, src/themes/money/package.json, src/themes/money/theme.json, src/themes/uswitch/CHANGELOG.md, src/themes/uswitch/package.json, src/themes/uswitch/theme.json
Ticket: https://rvu.atlassian.net/browse/MONEY-369
Related pr: https://github.com/uswitch/recharge-eevee/pull/1081
=> fix: styling for fiels that are on one line

src/compounds/billboard/CHANGELOG.md, src/compounds/billboard/package.json, src/compounds/billboard/src/index.tsx
Font sizes were added in code with * symbol so they increased the link size in dropdowns included in the billboard element. Removed this.
Related to this ticket: https://rvu.atlassian.net/browse/MONEY-731
=> removed font sizes which were increasing list item text

src/themes/money/CHANGELOG.md, src/themes/money/package.json, src/themes/money/theme.json
This is styling for the Credit Cards Result email sprint, figma here: https://www.figma.com/file/e3hYU0JEKGT9PvfzNGVrD2/Credit-Card-Results-Email?node-id=133%3A728
=> feat: add styling for money consent capture

src/themes/money/CHANGELOG.md, src/themes/money/package.json, src/themes/money/theme.json
So that it will not change style during 
checked: 
focus + hover 
=> Consent question bg checked easy fix

src/compounds/product-table/CHANGELOG.md, src/compounds/product-table/package.json, src/compounds/product-table/src/generics.ts
Adds formatter for adding commas to pound values, eg. £100,000
=> feat: adds formatter for pounds with commas

src/compounds/billboard/CHANGELOG.md, src/compounds/billboard/package.json, src/compounds/billboard/src/index.tsx, src/compounds/billboard/src/stories.tsx
Added variables to be able to control the image positioning and display on mobile.
Related to PR: https://github.com/uswitch/contentful-components/pull/512
Related to ticket: https://rvu.atlassian.net/browse/MONEY-839
Desktop:
Mobile:
=> billboard component image position and image mobile options

src/elements/link-list/src/index.tsx, src/elements/link-list/src/stories.tsx, src/themes/money/theme.json, src/themes/uswitch/theme.json
Link block variant for link-list had responsive fixed width; this caused issues when multiple link blocks were displayed next to each other, and did not fit their container width-wise. This PR makes them take up 100% of the container.
=> fix: link blocks having fixed widths, resulting in overlap

src/compounds/sponsored-product/CHANGELOG.md, src/compounds/sponsored-product/package.json, src/compounds/sponsored-product/src/index.tsx
Setting the trim color to be white, rather than the default top left pixel
This was set to black when handling the john lewis broadband logo, so it trimmed all of the black text
=> feat: added trim color to be white

src/themes/money/theme.json, src/themes/uswitch/theme.json
If size and weight are specified as a single value, they will apply only to the mobile view - and on larger sizes will be overridden. This issue is not observable when running storybook locally, but can be seen when the component is rendered in the context of `fs-core`:
After applying changes in this PR:
=> fix(link-list/linkBlock): specify explicit font size and weight

src/elements/author-profile/CHANGELOG.md, src/elements/author-profile/package.json, src/elements/author-profile/src/index.tsx
Update Author Name and Role to h1 instead of h2 on all Author Pages https://rvu.atlassian.net/browse/MONEY-1970
=> fix: update author name to use h1 instead of h2
